package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	bigtableservice "github.com/BishopFox/cloudfox/gcp/services/bigtableService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPBigtableCommand = &cobra.Command{
	Use:     globals.GCP_BIGTABLE_MODULE_NAME,
	Aliases: []string{"bt"},
	Short:   "Enumerate Cloud Bigtable instances",
	Long:    `Enumerate Cloud Bigtable instances, clusters, and tables.`,
	Run:     runGCPBigtableCommand,
}

type BigtableModule struct {
	gcpinternal.BaseGCPModule
	Instances []bigtableservice.BigtableInstanceInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type BigtableOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o BigtableOutput) TableFiles() []internal.TableFile { return o.Table }
func (o BigtableOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPBigtableCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_BIGTABLE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &BigtableModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []bigtableservice.BigtableInstanceInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *BigtableModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_BIGTABLE_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 {
		logger.InfoM("No Bigtable instances found", globals.GCP_BIGTABLE_MODULE_NAME)
		return
	}

	tableCount := 0
	for _, instance := range m.Instances {
		tableCount += len(instance.Tables)
	}

	logger.SuccessM(fmt.Sprintf("Found %d Bigtable instance(s) with %d table(s)",
		len(m.Instances), tableCount), globals.GCP_BIGTABLE_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *BigtableModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	svc := bigtableservice.New()
	instances, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_BIGTABLE_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Bigtable instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Instances = append(m.Instances, instances...)
	for _, instance := range instances {
		m.addToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *BigtableModule) initializeLootFiles() {
	m.LootMap["bigtable-instances"] = &internal.LootFile{
		Name:     "bigtable-instances",
		Contents: "# Bigtable Instances\n# Generated by CloudFox\n\n",
	}
}

func (m *BigtableModule) addToLoot(instance bigtableservice.BigtableInstanceInfo) {
	m.LootMap["bigtable-instances"].Contents += fmt.Sprintf(
		"# Instance: %s (%s)\n# Type: %s\n# Tables: %s\n# Clusters: %d\n\n",
		instance.Name, instance.DisplayName, instance.Type,
		strings.Join(instance.Tables, ", "),
		len(instance.Clusters))
}

func (m *BigtableModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{"Name", "Display Name", "Type", "Tables", "Clusters", "State", "Project Name", "Project"}

	var body [][]string
	for _, instance := range m.Instances {
		body = append(body, []string{
			instance.Name,
			instance.DisplayName,
			instance.Type,
			strings.Join(instance.Tables, ", "),
			fmt.Sprintf("%d", len(instance.Clusters)),
			instance.State,
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := BigtableOutput{
		Table: []internal.TableFile{{Name: "bigtable", Header: header, Body: body}},
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
}
