package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	bigtableservice "github.com/BishopFox/cloudfox/gcp/services/bigtableService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPBigtableCommand = &cobra.Command{
	Use:     globals.GCP_BIGTABLE_MODULE_NAME,
	Aliases: []string{"bt"},
	Short:   "Enumerate Cloud Bigtable instances and tables",
	Long: `Enumerate Cloud Bigtable instances, clusters, and tables with IAM analysis.

Features:
- Lists all Bigtable instances with instance-level IAM bindings
- Lists all tables with table-level IAM bindings
- Identifies publicly accessible instances and tables
- Shows cluster information per instance`,
	Run: runGCPBigtableCommand,
}

type BigtableModule struct {
	gcpinternal.BaseGCPModule
	ProjectInstances map[string][]bigtableservice.BigtableInstanceInfo // projectID -> instances
	ProjectTables    map[string][]bigtableservice.BigtableTableInfo    // projectID -> tables
	LootMap          map[string]map[string]*internal.LootFile          // projectID -> loot files
	mu               sync.Mutex
}

type BigtableOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o BigtableOutput) TableFiles() []internal.TableFile { return o.Table }
func (o BigtableOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPBigtableCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_BIGTABLE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &BigtableModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectInstances: make(map[string][]bigtableservice.BigtableInstanceInfo),
		ProjectTables:    make(map[string][]bigtableservice.BigtableTableInfo),
		LootMap:          make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *BigtableModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_BIGTABLE_MODULE_NAME, m.processProject)

	allInstances := m.getAllInstances()
	allTables := m.getAllTables()

	if len(allInstances) == 0 {
		logger.InfoM("No Bigtable instances found", globals.GCP_BIGTABLE_MODULE_NAME)
		return
	}

	// Count public instances and tables
	publicInstanceCount := 0
	publicTableCount := 0
	for _, instance := range allInstances {
		if instance.PublicAccess {
			publicInstanceCount++
		}
	}
	for _, table := range allTables {
		if table.PublicAccess {
			publicTableCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d instance(s) with %d table(s)",
		len(allInstances), len(allTables)), globals.GCP_BIGTABLE_MODULE_NAME)

	if publicInstanceCount > 0 || publicTableCount > 0 {
		logger.InfoM(fmt.Sprintf("[FINDING] Found %d public instance(s), %d public table(s)!",
			publicInstanceCount, publicTableCount), globals.GCP_BIGTABLE_MODULE_NAME)
	}

	m.writeOutput(ctx, logger)
}

func (m *BigtableModule) getAllInstances() []bigtableservice.BigtableInstanceInfo {
	var all []bigtableservice.BigtableInstanceInfo
	for _, instances := range m.ProjectInstances {
		all = append(all, instances...)
	}
	return all
}

func (m *BigtableModule) getAllTables() []bigtableservice.BigtableTableInfo {
	var all []bigtableservice.BigtableTableInfo
	for _, tables := range m.ProjectTables {
		all = append(all, tables...)
	}
	return all
}

func (m *BigtableModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Bigtable in project: %s", projectID), globals.GCP_BIGTABLE_MODULE_NAME)
	}

	svc := bigtableservice.New()
	result, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_BIGTABLE_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Bigtable instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.ProjectInstances[projectID] = result.Instances
	m.ProjectTables[projectID] = result.Tables

	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["bigtable-commands"] = &internal.LootFile{
			Name:     "bigtable-commands",
			Contents: "# Bigtable Commands\n# Generated by CloudFox\n\n",
		}
	}

	for _, instance := range result.Instances {
		m.addInstanceToLoot(projectID, instance)
	}
	for _, table := range result.Tables {
		m.addTableToLoot(projectID, table)
	}
	m.mu.Unlock()
}

func (m *BigtableModule) addInstanceToLoot(projectID string, instance bigtableservice.BigtableInstanceInfo) {
	lootFile := m.LootMap[projectID]["bigtable-commands"]
	if lootFile == nil {
		return
	}

	var clusterNames []string
	for _, cluster := range instance.Clusters {
		clusterNames = append(clusterNames, cluster.Name)
	}

	lootFile.Contents += fmt.Sprintf(
		"# Instance: %s (%s)\n"+
			"# Type: %s, State: %s\n"+
			"# Clusters: %s\n"+
			"cbt -project %s -instance %s ls\n\n",
		instance.Name, instance.DisplayName,
		instance.Type, instance.State,
		strings.Join(clusterNames, ", "),
		instance.ProjectID, instance.Name,
	)
}

func (m *BigtableModule) addTableToLoot(projectID string, table bigtableservice.BigtableTableInfo) {
	lootFile := m.LootMap[projectID]["bigtable-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# Table: %s (Instance: %s)\n"+
			"cbt -project %s -instance %s read %s count=10\n\n",
		table.Name, table.InstanceName,
		table.ProjectID, table.InstanceName, table.Name,
	)
}

func (m *BigtableModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *BigtableModule) getInstanceHeader() []string {
	return []string{"Project Name", "Project ID", "Instance", "Display Name", "Type", "State", "Clusters", "Resource Role", "Resource Principal", "Public"}
}

func (m *BigtableModule) getTableHeader() []string {
	return []string{"Project Name", "Project ID", "Instance", "Table", "Resource Role", "Resource Principal", "Public"}
}

func (m *BigtableModule) instancesToTableBody(instances []bigtableservice.BigtableInstanceInfo) [][]string {
	var body [][]string
	for _, instance := range instances {
		publicAccess := "No"
		if instance.PublicAccess {
			publicAccess = "Yes"
		}

		var clusterDetails []string
		for _, cluster := range instance.Clusters {
			clusterDetails = append(clusterDetails, fmt.Sprintf("%s (%s)", cluster.Name, cluster.Location))
		}
		clusters := "-"
		if len(clusterDetails) > 0 {
			clusters = strings.Join(clusterDetails, ", ")
		}

		if len(instance.IAMBindings) == 0 {
			body = append(body, []string{
				m.GetProjectName(instance.ProjectID),
				instance.ProjectID,
				instance.Name,
				instance.DisplayName,
				instance.Type,
				instance.State,
				clusters,
				"-",
				"-",
				publicAccess,
			})
		} else {
			for _, binding := range instance.IAMBindings {
				for _, member := range binding.Members {
					body = append(body, []string{
						m.GetProjectName(instance.ProjectID),
						instance.ProjectID,
						instance.Name,
						instance.DisplayName,
						instance.Type,
						instance.State,
						clusters,
						binding.Role,
						member,
						publicAccess,
					})
				}
			}
		}
	}
	return body
}

func (m *BigtableModule) tablesToTableBody(tables []bigtableservice.BigtableTableInfo) [][]string {
	var body [][]string
	for _, table := range tables {
		publicAccess := "No"
		if table.PublicAccess {
			publicAccess = "Yes"
		}

		if len(table.IAMBindings) == 0 {
			body = append(body, []string{
				m.GetProjectName(table.ProjectID),
				table.ProjectID,
				table.InstanceName,
				table.Name,
				"-",
				"-",
				publicAccess,
			})
		} else {
			for _, binding := range table.IAMBindings {
				for _, member := range binding.Members {
					body = append(body, []string{
						m.GetProjectName(table.ProjectID),
						table.ProjectID,
						table.InstanceName,
						table.Name,
						binding.Role,
						member,
						publicAccess,
					})
				}
			}
		}
	}
	return body
}

func (m *BigtableModule) buildTablesForProject(projectID string) []internal.TableFile {
	var tableFiles []internal.TableFile

	if instances, ok := m.ProjectInstances[projectID]; ok && len(instances) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "bigtable-instances",
			Header: m.getInstanceHeader(),
			Body:   m.instancesToTableBody(instances),
		})
	}

	if tables, ok := m.ProjectTables[projectID]; ok && len(tables) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "bigtable-tables",
			Header: m.getTableHeader(),
			Body:   m.tablesToTableBody(tables),
		})
	}

	return tableFiles
}

func (m *BigtableModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	for projectID := range m.ProjectInstances {
		tableFiles := m.buildTablesForProject(projectID)

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = BigtableOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
}

func (m *BigtableModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allInstances := m.getAllInstances()
	allTables := m.getAllTables()

	var tableFiles []internal.TableFile

	if len(allInstances) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "bigtable-instances",
			Header: m.getInstanceHeader(),
			Body:   m.instancesToTableBody(allInstances),
		})
	}

	if len(allTables) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   "bigtable-tables",
			Header: m.getTableHeader(),
			Body:   m.tablesToTableBody(allTables),
		})
	}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := BigtableOutput{
		Table: tableFiles,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
}
