package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	cloudbuildservice "github.com/BishopFox/cloudfox/gcp/services/cloudbuildService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPCloudBuildCommand = &cobra.Command{
	Use:     globals.GCP_CLOUDBUILD_MODULE_NAME,
	Aliases: []string{"cb", "build", "builds"},
	Short:   "Enumerate Cloud Build triggers and builds",
	Long: `Enumerate Cloud Build triggers and recent build executions.

Features:
- Lists all build triggers
- Shows trigger source configuration (GitHub, CSR)
- Identifies service accounts used for builds
- Shows recent build executions
- Detects potentially risky trigger configurations`,
	Run: runGCPCloudBuildCommand,
}

// ------------------------------
// Module Struct with embedded BaseGCPModule
// ------------------------------
type CloudBuildModule struct {
	gcpinternal.BaseGCPModule

	// Module-specific fields
	Triggers         []cloudbuildservice.TriggerInfo
	Builds           []cloudbuildservice.BuildInfo
	SecurityAnalysis []cloudbuildservice.TriggerSecurityAnalysis
	LootMap          map[string]*internal.LootFile
	mu               sync.Mutex
}

// ------------------------------
// Output Struct implementing CloudfoxOutput interface
// ------------------------------
type CloudBuildOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o CloudBuildOutput) TableFiles() []internal.TableFile { return o.Table }
func (o CloudBuildOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPCloudBuildCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_CLOUDBUILD_MODULE_NAME)
	if err != nil {
		return
	}

	module := &CloudBuildModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		Triggers:         []cloudbuildservice.TriggerInfo{},
		Builds:           []cloudbuildservice.BuildInfo{},
		SecurityAnalysis: []cloudbuildservice.TriggerSecurityAnalysis{},
		LootMap:          make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *CloudBuildModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_CLOUDBUILD_MODULE_NAME, m.processProject)

	if len(m.Triggers) == 0 && len(m.Builds) == 0 {
		logger.InfoM("No Cloud Build triggers or builds found", globals.GCP_CLOUDBUILD_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d trigger(s), %d recent build(s)",
		len(m.Triggers), len(m.Builds)), globals.GCP_CLOUDBUILD_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *CloudBuildModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Cloud Build in project: %s", projectID), globals.GCP_CLOUDBUILD_MODULE_NAME)
	}

	cbSvc := cloudbuildservice.New()

	// Get triggers
	triggers, err := cbSvc.ListTriggers(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_CLOUDBUILD_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Cloud Build triggers in project %s", projectID))
	}

	// Get recent builds
	builds, err := cbSvc.ListBuilds(projectID, 20)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_CLOUDBUILD_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Cloud Build builds in project %s", projectID))
	}

	m.mu.Lock()
	m.Triggers = append(m.Triggers, triggers...)
	m.Builds = append(m.Builds, builds...)

	for _, trigger := range triggers {
		m.addTriggerToLoot(trigger)
		// Perform security analysis
		analysis := cbSvc.AnalyzeTriggerForPrivesc(trigger, projectID)
		m.SecurityAnalysis = append(m.SecurityAnalysis, analysis)
		m.addSecurityAnalysisToLoot(analysis)
	}

	// Add build step analysis to loot
	for _, build := range builds {
		m.addBuildToLoot(build)
	}
	m.mu.Unlock()
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *CloudBuildModule) initializeLootFiles() {
	m.LootMap["cloudbuild-triggers"] = &internal.LootFile{
		Name:     "cloudbuild-triggers",
		Contents: "# Cloud Build Triggers\n# Generated by CloudFox\n\n",
	}
	m.LootMap["cloudbuild-service-accounts"] = &internal.LootFile{
		Name:     "cloudbuild-service-accounts",
		Contents: "# Cloud Build Service Accounts\n# Generated by CloudFox\n\n",
	}
	// Pentest-focused loot files
	m.LootMap["cloudbuild-privesc"] = &internal.LootFile{
		Name:     "cloudbuild-privesc",
		Contents: "# Cloud Build Privilege Escalation Opportunities\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
	m.LootMap["cloudbuild-exploitation"] = &internal.LootFile{
		Name:     "cloudbuild-exploitation",
		Contents: "# Cloud Build Exploitation Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
	m.LootMap["cloudbuild-secrets"] = &internal.LootFile{
		Name:     "cloudbuild-secrets",
		Contents: "# Cloud Build Secret References\n# Generated by CloudFox\n# Secrets used in builds (names only, not values)\n\n",
	}
	m.LootMap["cloudbuild-logs"] = &internal.LootFile{
		Name:     "cloudbuild-logs",
		Contents: "# Cloud Build Log Locations\n# Generated by CloudFox\n# Check logs for leaked secrets\n\n",
	}
}

func (m *CloudBuildModule) addTriggerToLoot(trigger cloudbuildservice.TriggerInfo) {
	m.LootMap["cloudbuild-triggers"].Contents += fmt.Sprintf(
		"# Trigger: %s (%s)\n"+
			"# Source: %s - %s\n"+
			"# Branch: %s\n"+
			"# Config: %s\n\n",
		trigger.Name,
		trigger.ID,
		trigger.SourceType,
		trigger.RepoName,
		trigger.BranchName,
		trigger.Filename,
	)

	if trigger.ServiceAccount != "" {
		m.LootMap["cloudbuild-service-accounts"].Contents += fmt.Sprintf(
			"%s # Trigger: %s\n",
			trigger.ServiceAccount,
			trigger.Name,
		)
	}
}

func (m *CloudBuildModule) addSecurityAnalysisToLoot(analysis cloudbuildservice.TriggerSecurityAnalysis) {
	if analysis.PrivescPotential || analysis.RiskLevel == "HIGH" || analysis.RiskLevel == "MEDIUM" {
		m.LootMap["cloudbuild-privesc"].Contents += fmt.Sprintf(
			"## [%s] Trigger: %s\n"+
				"## Project: %s\n"+
				"## Service Account: %s\n"+
				"## Privesc Potential: %v\n",
			analysis.RiskLevel, analysis.TriggerName,
			analysis.ProjectID,
			analysis.ServiceAccount,
			analysis.PrivescPotential,
		)
		if len(analysis.RiskReasons) > 0 {
			m.LootMap["cloudbuild-privesc"].Contents += "## Risk Reasons:\n"
			for _, reason := range analysis.RiskReasons {
				m.LootMap["cloudbuild-privesc"].Contents += fmt.Sprintf("##   - %s\n", reason)
			}
		}
		m.LootMap["cloudbuild-privesc"].Contents += "\n"
	}

	// Exploitation commands
	if len(analysis.ExploitCommands) > 0 {
		m.LootMap["cloudbuild-exploitation"].Contents += fmt.Sprintf(
			"## Trigger: %s (Project: %s)\n"+
				"## Risk: %s\n",
			analysis.TriggerName, analysis.ProjectID, analysis.RiskLevel,
		)
		for _, cmd := range analysis.ExploitCommands {
			m.LootMap["cloudbuild-exploitation"].Contents += cmd + "\n"
		}
		m.LootMap["cloudbuild-exploitation"].Contents += "\n"
	}
}

func (m *CloudBuildModule) addBuildToLoot(build cloudbuildservice.BuildInfo) {
	// Log locations for potential secret leakage
	if build.LogsBucket != "" {
		m.LootMap["cloudbuild-logs"].Contents += fmt.Sprintf(
			"# Build: %s (Project: %s)\n"+
				"# Status: %s\n"+
				"gsutil cat %s/log-%s.txt\n\n",
			build.ID[:12], build.ProjectID, build.Status,
			build.LogsBucket, build.ID,
		)
	}

	// Track secrets used in builds
	if len(build.SecretEnvVars) > 0 {
		m.LootMap["cloudbuild-secrets"].Contents += fmt.Sprintf(
			"## Build: %s (Project: %s)\n"+
				"## Secret Environment Variables:\n",
			build.ID[:12], build.ProjectID,
		)
		for _, secret := range build.SecretEnvVars {
			m.LootMap["cloudbuild-secrets"].Contents += fmt.Sprintf("##   - %s\n", secret)
		}
		m.LootMap["cloudbuild-secrets"].Contents += "\n"
	}
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *CloudBuildModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Triggers table
	triggersHeader := []string{
		"Name",
		"Source",
		"Repository",
		"Branch/Tag",
		"Config File",
		"Service Account",
		"Disabled",
		"Project Name",
		"Project",
	}

	var triggersBody [][]string
	for _, trigger := range m.Triggers {
		disabled := ""
		if trigger.Disabled {
			disabled = "Yes"
		}

		branchTag := trigger.BranchName
		if branchTag == "" {
			branchTag = trigger.TagName
		}

		sa := trigger.ServiceAccount
		if sa == "" {
			sa = "(default)"
		}

		triggersBody = append(triggersBody, []string{
			trigger.Name,
			trigger.SourceType,
			trigger.RepoName,
			branchTag,
			trigger.Filename,
			sa,
			disabled,
			m.GetProjectName(trigger.ProjectID),
			trigger.ProjectID,
		})
	}

	// Builds table
	buildsHeader := []string{
		"ID",
		"Status",
		"Trigger",
		"Source",
		"Created",
		"Project Name",
		"Project",
	}

	var buildsBody [][]string
	for _, build := range m.Builds {
		buildsBody = append(buildsBody, []string{
			build.ID[:12],
			build.Status,
			build.TriggerID,
			build.Source,
			build.CreateTime,
			m.GetProjectName(build.ProjectID),
			build.ProjectID,
		})
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{
		{
			Name:   "cloudbuild-triggers",
			Header: triggersHeader,
			Body:   triggersBody,
		},
	}

	if len(buildsBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "cloudbuild-builds",
			Header: buildsHeader,
			Body:   buildsBody,
		})
	}

	// Security analysis table (pentest-focused)
	securityHeader := []string{
		"Risk",
		"Trigger",
		"Service Account",
		"Privesc",
		"Reasons",
		"Project Name",
		"Project",
	}

	var securityBody [][]string
	privescCount := 0
	for _, analysis := range m.SecurityAnalysis {
		privesc := ""
		if analysis.PrivescPotential {
			privesc = "Yes"
			privescCount++
		}

		reasons := strings.Join(analysis.RiskReasons, "; ")
		if len(reasons) > 50 {
			reasons = reasons[:50] + "..."
		}

		securityBody = append(securityBody, []string{
			analysis.RiskLevel,
			analysis.TriggerName,
			analysis.ServiceAccount,
			privesc,
			reasons,
			m.GetProjectName(analysis.ProjectID),
			analysis.ProjectID,
		})
	}

	if len(securityBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "cloudbuild-security",
			Header: securityHeader,
			Body:   securityBody,
		})
		if privescCount > 0 {
			logger.InfoM(fmt.Sprintf("[PENTEST] Found %d trigger(s) with privilege escalation potential!", privescCount), globals.GCP_CLOUDBUILD_MODULE_NAME)
		}
	}

	output := CloudBuildOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_CLOUDBUILD_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
