package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	composerservice "github.com/BishopFox/cloudfox/gcp/services/composerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPComposerCommand = &cobra.Command{
	Use:     globals.GCP_COMPOSER_MODULE_NAME,
	Aliases: []string{"airflow"},
	Short:   "Enumerate Cloud Composer environments",
	Long: `Enumerate Cloud Composer (managed Apache Airflow) environments.

Features:
- Lists all Composer environments across locations
- Shows Airflow web UI endpoints
- Identifies service account configuration
- Analyzes network exposure (private vs public)
- Detects overly permissive IP restrictions`,
	Run: runGCPComposerCommand,
}

type ComposerModule struct {
	gcpinternal.BaseGCPModule
	ProjectEnvironments map[string][]composerservice.EnvironmentInfo // projectID -> environments
	LootMap             map[string]map[string]*internal.LootFile     // projectID -> loot files
	AttackPathCache     *gcpinternal.AttackPathCache                 // Cached attack path analysis results
	mu                  sync.Mutex
}

type ComposerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o ComposerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o ComposerOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPComposerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_COMPOSER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &ComposerModule{
		BaseGCPModule:       gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectEnvironments: make(map[string][]composerservice.EnvironmentInfo),
		LootMap:             make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *ComposerModule) Execute(ctx context.Context, logger internal.Logger) {
	// Get attack path cache from context (populated by all-checks or attack path analysis)
	m.AttackPathCache = gcpinternal.GetAttackPathCacheFromContext(ctx)

	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_COMPOSER_MODULE_NAME, m.processProject)

	allEnvironments := m.getAllEnvironments()
	if len(allEnvironments) == 0 {
		logger.InfoM("No Composer environments found", globals.GCP_COMPOSER_MODULE_NAME)
		return
	}

	// Count by state
	running := 0
	publicEnvs := 0
	for _, env := range allEnvironments {
		if env.State == "RUNNING" {
			running++
		}
		if !env.PrivateEnvironment {
			publicEnvs++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Composer environment(s) (%d running, %d public)",
		len(allEnvironments), running, publicEnvs), globals.GCP_COMPOSER_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *ComposerModule) getAllEnvironments() []composerservice.EnvironmentInfo {
	var all []composerservice.EnvironmentInfo
	for _, envs := range m.ProjectEnvironments {
		all = append(all, envs...)
	}
	return all
}

func (m *ComposerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Composer in project: %s", projectID), globals.GCP_COMPOSER_MODULE_NAME)
	}

	svc := composerservice.New()
	environments, err := svc.ListEnvironments(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_COMPOSER_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Composer environments in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.ProjectEnvironments[projectID] = environments

	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["composer-commands"] = &internal.LootFile{
			Name:     "composer-commands",
			Contents: "# Composer Commands\n# Generated by CloudFox\n\n",
		}
	}

	for _, env := range environments {
		m.addToLoot(projectID, env)
	}
	m.mu.Unlock()
}

func (m *ComposerModule) addToLoot(projectID string, env composerservice.EnvironmentInfo) {
	lootFile := m.LootMap[projectID]["composer-commands"]
	if lootFile == nil {
		return
	}
	lootFile.Contents += fmt.Sprintf(
		"# %s (%s)\n"+
			"# Project: %s\n",
		env.Name, env.Location,
		env.ProjectID,
	)

	// gcloud commands
	lootFile.Contents += fmt.Sprintf(
		"gcloud composer environments describe %s --location=%s --project=%s\n"+
			"gcloud composer environments run %s --location=%s --project=%s dags list\n",
		env.Name, env.Location, env.ProjectID,
		env.Name, env.Location, env.ProjectID,
	)

	// DAG bucket command
	if env.DagGcsPrefix != "" {
		lootFile.Contents += fmt.Sprintf(
			"gsutil ls %s\n",
			env.DagGcsPrefix,
		)
	}

	// Airflow Web UI
	if env.AirflowURI != "" {
		lootFile.Contents += fmt.Sprintf(
			"# Airflow Web UI: %s\n",
			env.AirflowURI,
		)
	}

	lootFile.Contents += "\n"
}

func (m *ComposerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *ComposerModule) getTableHeader() []string {
	return []string{
		"Project Name",
		"Project ID",
		"Name",
		"Location",
		"State",
		"Service Account",
		"Attack Paths",
		"Private",
		"Private Endpoint",
		"Airflow URI",
		"DAG Bucket",
		"Image Version",
	}
}

func (m *ComposerModule) environmentsToTableBody(environments []composerservice.EnvironmentInfo) [][]string {
	var body [][]string
	for _, env := range environments {
		sa := env.ServiceAccount
		if sa == "" {
			sa = "(default)"
		}

		// Check attack paths (privesc/exfil/lateral) for the service account
		attackPaths := "-"
		if m.AttackPathCache != nil && m.AttackPathCache.IsPopulated() {
			if sa != "(default)" && sa != "" {
				attackPaths = m.AttackPathCache.GetAttackSummary(sa)
			} else {
				attackPaths = "No"
			}
		}

		airflowURI := env.AirflowURI
		if airflowURI == "" {
			airflowURI = "-"
		}

		dagBucket := env.DagGcsPrefix
		if dagBucket == "" {
			dagBucket = "-"
		}

		imageVersion := env.ImageVersion
		if imageVersion == "" {
			imageVersion = "-"
		}

		body = append(body, []string{
			m.GetProjectName(env.ProjectID),
			env.ProjectID,
			env.Name,
			env.Location,
			env.State,
			sa,
			attackPaths,
			boolToYesNo(env.PrivateEnvironment),
			boolToYesNo(env.EnablePrivateEndpoint),
			airflowURI,
			dagBucket,
			imageVersion,
		})
	}
	return body
}

func (m *ComposerModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	for projectID, environments := range m.ProjectEnvironments {
		body := m.environmentsToTableBody(environments)
		tableFiles := []internal.TableFile{{Name: "composer", Header: m.getTableHeader(), Body: body}}

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = ComposerOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_COMPOSER_MODULE_NAME)
	}
}

func (m *ComposerModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allEnvironments := m.getAllEnvironments()
	body := m.environmentsToTableBody(allEnvironments)

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	tables := []internal.TableFile{{Name: "composer", Header: m.getTableHeader(), Body: body}}
	output := ComposerOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_COMPOSER_MODULE_NAME)
	}
}
