package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	composerservice "github.com/BishopFox/cloudfox/gcp/services/composerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPComposerCommand = &cobra.Command{
	Use:     globals.GCP_COMPOSER_MODULE_NAME,
	Aliases: []string{"airflow"},
	Short:   "Enumerate Cloud Composer environments",
	Long: `Enumerate Cloud Composer (managed Apache Airflow) environments.

Features:
- Lists all Composer environments across locations
- Shows Airflow web UI endpoints
- Identifies service account configuration
- Analyzes network exposure (private vs public)
- Detects overly permissive IP restrictions`,
	Run: runGCPComposerCommand,
}

type ComposerModule struct {
	gcpinternal.BaseGCPModule
	Environments []composerservice.EnvironmentInfo
	LootMap      map[string]*internal.LootFile
	mu           sync.Mutex
}

type ComposerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o ComposerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o ComposerOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPComposerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_COMPOSER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &ComposerModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Environments:  []composerservice.EnvironmentInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *ComposerModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_COMPOSER_MODULE_NAME, m.processProject)

	if len(m.Environments) == 0 {
		logger.InfoM("No Composer environments found", globals.GCP_COMPOSER_MODULE_NAME)
		return
	}

	// Count by state
	running := 0
	publicEnvs := 0
	for _, env := range m.Environments {
		if env.State == "RUNNING" {
			running++
		}
		if !env.PrivateEnvironment {
			publicEnvs++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Composer environment(s) (%d running, %d public)",
		len(m.Environments), running, publicEnvs), globals.GCP_COMPOSER_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *ComposerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Composer in project: %s", projectID), globals.GCP_COMPOSER_MODULE_NAME)
	}

	svc := composerservice.New()
	environments, err := svc.ListEnvironments(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_COMPOSER_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Composer environments in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Environments = append(m.Environments, environments...)
	for _, env := range environments {
		m.addToLoot(env)
	}
	m.mu.Unlock()
}

func (m *ComposerModule) initializeLootFiles() {
	m.LootMap["composer-environments"] = &internal.LootFile{
		Name:     "composer-environments",
		Contents: "# Composer Environments\n# Generated by CloudFox\n\n",
	}
	m.LootMap["composer-airflow-urls"] = &internal.LootFile{
		Name:     "composer-airflow-urls",
		Contents: "",
	}
	m.LootMap["composer-dag-buckets"] = &internal.LootFile{
		Name:     "composer-dag-buckets",
		Contents: "",
	}
}

func (m *ComposerModule) addToLoot(env composerservice.EnvironmentInfo) {
	m.LootMap["composer-environments"].Contents += fmt.Sprintf(
		"# Environment: %s\n# State: %s\n# Service Account: %s\n# Private: %v\n# Airflow URI: %s\n\n",
		env.Name, env.State, env.ServiceAccount, env.PrivateEnvironment, env.AirflowURI)

	if env.AirflowURI != "" {
		m.LootMap["composer-airflow-urls"].Contents += env.AirflowURI + "\n"
	}

	if env.DagGcsPrefix != "" {
		m.LootMap["composer-dag-buckets"].Contents += env.DagGcsPrefix + "\n"
	}
}

func (m *ComposerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Name", "State", "Location", "Service Account",
		"Private", "Airflow URI", "Risk", "Project Name", "Project",
	}

	var body [][]string
	for _, env := range m.Environments {
		private := "No"
		if env.PrivateEnvironment {
			private = "Yes"
		}

		sa := env.ServiceAccount
		if sa == "" {
			sa = "(default)"
		} else if len(sa) > 40 {
			sa = sa[:37] + "..."
		}

		airflowURI := env.AirflowURI
		if len(airflowURI) > 50 {
			airflowURI = airflowURI[:47] + "..."
		}

		body = append(body, []string{
			env.Name,
			env.State,
			env.Location,
			sa,
			private,
			airflowURI,
			env.RiskLevel,
			m.GetProjectName(env.ProjectID),
			env.ProjectID,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{{Name: "composer", Header: header, Body: body}}

	// High-risk environments table
	var highRiskBody [][]string
	for _, env := range m.Environments {
		if env.RiskLevel == "HIGH" || env.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				env.Name,
				env.RiskLevel,
				strings.Join(env.RiskReasons, "; "),
				m.GetProjectName(env.ProjectID),
				env.ProjectID,
			})
		}
	}

	if len(highRiskBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "composer-risks",
			Header: []string{"Environment", "Risk Level", "Reasons", "Project Name", "Project"},
			Body:   highRiskBody,
		})
	}

	output := ComposerOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_COMPOSER_MODULE_NAME)
	}
}
