package commands

import (
	"github.com/BishopFox/cloudfox/gcp/shared"
	"context"
	"fmt"
	"strings"
	"sync"

	dataprocservice "github.com/BishopFox/cloudfox/gcp/services/dataprocService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPDataprocCommand = &cobra.Command{
	Use:     globals.GCP_DATAPROC_MODULE_NAME,
	Aliases: []string{"dp", "hadoop", "spark"},
	Short:   "Enumerate Dataproc clusters",
	Long: `Enumerate Dataproc (Hadoop/Spark) clusters.

Features:
- Lists all Dataproc clusters across regions
- Shows service account configuration
- Identifies public IP exposure
- Checks for Kerberos authentication
- Analyzes security configurations`,
	Run: runGCPDataprocCommand,
}

type DataprocModule struct {
	gcpinternal.BaseGCPModule
	ProjectClusters map[string][]dataprocservice.ClusterInfo // projectID -> clusters
	LootMap         map[string]map[string]*internal.LootFile // projectID -> loot files
	FoxMapperCache  *gcpinternal.FoxMapperCache              // Cached FoxMapper results
	mu              sync.Mutex
}

type DataprocOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o DataprocOutput) TableFiles() []internal.TableFile { return o.Table }
func (o DataprocOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPDataprocCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_DATAPROC_MODULE_NAME)
	if err != nil {
		return
	}

	module := &DataprocModule{
		BaseGCPModule:   gcpinternal.NewBaseGCPModule(cmdCtx),
		ProjectClusters: make(map[string][]dataprocservice.ClusterInfo),
		LootMap:         make(map[string]map[string]*internal.LootFile),
	}
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *DataprocModule) Execute(ctx context.Context, logger internal.Logger) {
	// Get FoxMapper cache from context
	m.FoxMapperCache = gcpinternal.GetFoxMapperCacheFromContext(ctx)

	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_DATAPROC_MODULE_NAME, m.processProject)

	allClusters := m.getAllClusters()
	if len(allClusters) == 0 {
		logger.InfoM("No Dataproc clusters found", globals.GCP_DATAPROC_MODULE_NAME)
		return
	}

	runningCount := 0
	publicCount := 0
	for _, cluster := range allClusters {
		if cluster.State == "RUNNING" {
			runningCount++
		}
		if !cluster.InternalIPOnly {
			publicCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Dataproc cluster(s) (%d running, %d with public IPs)",
		len(allClusters), runningCount, publicCount), globals.GCP_DATAPROC_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *DataprocModule) getAllClusters() []dataprocservice.ClusterInfo {
	var all []dataprocservice.ClusterInfo
	for _, clusters := range m.ProjectClusters {
		all = append(all, clusters...)
	}
	return all
}

func (m *DataprocModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Dataproc in project: %s", projectID), globals.GCP_DATAPROC_MODULE_NAME)
	}

	svc := dataprocservice.New()

	clusters, err := svc.ListClusters(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_DATAPROC_MODULE_NAME,
			fmt.Sprintf("Could not list Dataproc clusters in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.ProjectClusters[projectID] = clusters

	// Initialize loot for this project
	if m.LootMap[projectID] == nil {
		m.LootMap[projectID] = make(map[string]*internal.LootFile)
		m.LootMap[projectID]["dataproc-commands"] = &internal.LootFile{
			Name:     "dataproc-commands",
			Contents: "# Dataproc Commands\n# Generated by CloudFox\n\n",
		}
	}

	for _, cluster := range clusters {
		m.addToLoot(projectID, cluster)
	}
	m.mu.Unlock()
}

func (m *DataprocModule) addToLoot(projectID string, cluster dataprocservice.ClusterInfo) {
	lootFile := m.LootMap[projectID]["dataproc-commands"]
	if lootFile == nil {
		return
	}

	lootFile.Contents += fmt.Sprintf(
		"# %s (%s)\n"+
			"# Project: %s\n",
		cluster.Name, cluster.Region,
		cluster.ProjectID,
	)

	// gcloud commands
	lootFile.Contents += fmt.Sprintf(
		"gcloud dataproc clusters describe %s --region=%s --project=%s\n"+
			"gcloud dataproc jobs list --cluster=%s --region=%s --project=%s\n",
		cluster.Name, cluster.Region, cluster.ProjectID,
		cluster.Name, cluster.Region, cluster.ProjectID,
	)

	// Bucket commands
	if cluster.ConfigBucket != "" {
		lootFile.Contents += fmt.Sprintf(
			"gsutil ls gs://%s/\n",
			cluster.ConfigBucket,
		)
	}
	if cluster.TempBucket != "" {
		lootFile.Contents += fmt.Sprintf(
			"gsutil ls gs://%s/\n",
			cluster.TempBucket,
		)
	}

	lootFile.Contents += "\n"
}

func (m *DataprocModule) writeOutput(ctx context.Context, logger internal.Logger) {
	if m.Hierarchy != nil && !m.FlatOutput {
		m.writeHierarchicalOutput(ctx, logger)
	} else {
		m.writeFlatOutput(ctx, logger)
	}
}

func (m *DataprocModule) getTableHeader() []string {
	return []string{
		"Project",
		"Name",
		"Region",
		"State",
		"Master",
		"Master Instances",
		"Workers",
		"Service Account",
		"SA Attack Paths",
		"Public IPs",
		"Kerberos",
		"IAM Binding Role",
		"IAM Binding Principal",
	}
}

func (m *DataprocModule) clustersToTableBody(clusters []dataprocservice.ClusterInfo) [][]string {
	var body [][]string
	for _, cluster := range clusters {
		sa := cluster.ServiceAccount
		if sa == "" {
			sa = "(default)"
		}

		// Check attack paths (privesc/exfil/lateral) for the service account
		attackPaths := "run foxmapper"
		if m.FoxMapperCache != nil && m.FoxMapperCache.IsPopulated() {
			if sa != "(default)" && sa != "" {
				attackPaths = gcpinternal.GetAttackSummaryFromCaches(m.FoxMapperCache, nil, sa)
			} else {
				attackPaths = "No"
			}
		}

		masterConfig := fmt.Sprintf("%s x%d", cluster.MasterMachineType, cluster.MasterCount)
		workerConfig := fmt.Sprintf("%s x%d", cluster.WorkerMachineType, cluster.WorkerCount)

		// Master instances
		masterInstances := "-"
		if len(cluster.MasterInstanceNames) > 0 {
			masterInstances = strings.Join(cluster.MasterInstanceNames, ", ")
		}

		// If cluster has IAM bindings, create one row per binding
		if len(cluster.IAMBindings) > 0 {
			for _, binding := range cluster.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(cluster.ProjectID),
					cluster.Name,
					cluster.Region,
					cluster.State,
					masterConfig,
					masterInstances,
					workerConfig,
					sa,
					attackPaths,
					shared.BoolToYesNo(!cluster.InternalIPOnly),
					shared.BoolToYesNo(cluster.KerberosEnabled),
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Cluster has no IAM bindings - single row
			body = append(body, []string{
				m.GetProjectName(cluster.ProjectID),
				cluster.Name,
				cluster.Region,
				cluster.State,
				masterConfig,
				masterInstances,
				workerConfig,
				sa,
				attackPaths,
				shared.BoolToYesNo(!cluster.InternalIPOnly),
				shared.BoolToYesNo(cluster.KerberosEnabled),
				"-",
				"-",
			})
		}
	}
	return body
}

func (m *DataprocModule) writeHierarchicalOutput(ctx context.Context, logger internal.Logger) {
	outputData := internal.HierarchicalOutputData{
		OrgLevelData:     make(map[string]internal.CloudfoxOutput),
		ProjectLevelData: make(map[string]internal.CloudfoxOutput),
	}

	for projectID, clusters := range m.ProjectClusters {
		body := m.clustersToTableBody(clusters)
		tableFiles := []internal.TableFile{{Name: "dataproc-clusters", Header: m.getTableHeader(), Body: body}}

		var lootFiles []internal.LootFile
		if projectLoot, ok := m.LootMap[projectID]; ok {
			for _, loot := range projectLoot {
				if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
					lootFiles = append(lootFiles, *loot)
				}
			}
		}

		outputData.ProjectLevelData[projectID] = DataprocOutput{Table: tableFiles, Loot: lootFiles}
	}

	pathBuilder := m.BuildPathBuilder()

	err := internal.HandleHierarchicalOutputSmart("gcp", m.Format, m.Verbosity, m.WrapTable, pathBuilder, outputData)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing hierarchical output: %v", err), globals.GCP_DATAPROC_MODULE_NAME)
	}
}

func (m *DataprocModule) writeFlatOutput(ctx context.Context, logger internal.Logger) {
	allClusters := m.getAllClusters()
	body := m.clustersToTableBody(allClusters)

	tables := []internal.TableFile{{Name: "dataproc-clusters", Header: m.getTableHeader(), Body: body}}

	var lootFiles []internal.LootFile
	for _, projectLoot := range m.LootMap {
		for _, loot := range projectLoot {
			if loot != nil && loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
				lootFiles = append(lootFiles, *loot)
			}
		}
	}

	output := DataprocOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_DATAPROC_MODULE_NAME)
	}
}
