package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	filestoreservice "github.com/BishopFox/cloudfox/gcp/services/filestoreService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPFilestoreCommand = &cobra.Command{
	Use:     globals.GCP_FILESTORE_MODULE_NAME,
	Aliases: []string{"nfs", "files"},
	Short:   "Enumerate Filestore NFS instances",
	Long:    `Enumerate Filestore instances and their file shares.`,
	Run:     runGCPFilestoreCommand,
}

type FilestoreModule struct {
	gcpinternal.BaseGCPModule
	Instances []filestoreservice.FilestoreInstanceInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type FilestoreOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o FilestoreOutput) TableFiles() []internal.TableFile { return o.Table }
func (o FilestoreOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPFilestoreCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_FILESTORE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &FilestoreModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []filestoreservice.FilestoreInstanceInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *FilestoreModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_FILESTORE_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 {
		logger.InfoM("No Filestore instances found", globals.GCP_FILESTORE_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d Filestore instance(s)", len(m.Instances)), globals.GCP_FILESTORE_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *FilestoreModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	svc := filestoreservice.New()
	instances, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_FILESTORE_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Filestore instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Instances = append(m.Instances, instances...)
	for _, instance := range instances {
		m.addToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *FilestoreModule) initializeLootFiles() {
	m.LootMap["filestore-commands"] = &internal.LootFile{
		Name:     "filestore-commands",
		Contents: "# Filestore Commands\n# Generated by CloudFox\n\n",
	}
}

func (m *FilestoreModule) addToLoot(instance filestoreservice.FilestoreInstanceInfo) {
	// Determine protocol display name
	protocol := instance.Protocol
	if protocol == "" {
		protocol = "NFS_V3" // Default
	}

	m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
		"# ==========================================\n"+
			"# Instance: %s\n"+
			"# ==========================================\n"+
			"# Location: %s\n"+
			"# Project: %s\n"+
			"# Protocol: %s\n"+
			"# Tier: %s\n"+
			"# Network: %s\n"+
			"# IP(s): %s\n\n",
		instance.Name,
		instance.Location,
		instance.ProjectID,
		protocol,
		instance.Tier,
		instance.Network,
		strings.Join(instance.IPAddresses, ", "),
	)

	// gcloud describe command
	m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
		"# Describe instance:\n"+
			"gcloud filestore instances describe %s --location=%s --project=%s\n\n",
		instance.Name, instance.Location, instance.ProjectID,
	)

	// Mount commands for each share
	if len(instance.Shares) > 0 && len(instance.IPAddresses) > 0 {
		for _, share := range instance.Shares {
			m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
				"# ------------------------------------------\n"+
					"# Share: %s (%d GB)\n"+
					"# ------------------------------------------\n",
				share.Name, share.CapacityGB,
			)

			// Show NFS export options if present
			if len(share.NfsExportOptions) > 0 {
				m.LootMap["filestore-commands"].Contents += "# NFS Export Options:\n"
				for _, opt := range share.NfsExportOptions {
					ipRanges := strings.Join(opt.IPRanges, ", ")
					if ipRanges == "" {
						ipRanges = "all"
					}
					m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
						"#   IP Ranges: %s\n"+
							"#   Access: %s\n"+
							"#   Squash: %s\n",
						ipRanges,
						opt.AccessMode,
						opt.SquashMode,
					)
					if opt.SquashMode == "NO_ROOT_SQUASH" {
						m.LootMap["filestore-commands"].Contents += "#   [!] NO_ROOT_SQUASH - root access preserved!\n"
					}
				}
				m.LootMap["filestore-commands"].Contents += "\n"
			}

			// Generate mount commands based on protocol
			for _, ip := range instance.IPAddresses {
				m.LootMap["filestore-commands"].Contents += "# Mount commands (run as root):\n"

				switch protocol {
				case "NFS_V4_1":
					// NFSv4.1 mount command
					m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
						"# NFSv4.1 mount:\n"+
							"sudo mkdir -p /mnt/%s\n"+
							"sudo mount -t nfs -o vers=4.1 %s:/%s /mnt/%s\n"+
							"# With Kerberos (if configured):\n"+
							"# sudo mount -t nfs -o vers=4.1,sec=krb5p %s:/%s /mnt/%s\n\n",
						share.Name,
						ip, share.Name, share.Name,
						ip, share.Name, share.Name,
					)
				default: // NFS_V3 or empty
					// NFSv3 mount command
					m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
						"# NFSv3 mount:\n"+
							"sudo mkdir -p /mnt/%s\n"+
							"sudo mount -t nfs -o vers=3 %s:/%s /mnt/%s\n\n",
						share.Name,
						ip, share.Name, share.Name,
					)
				}

				// List contents after mounting
				m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
					"# After mounting, list contents:\n"+
						"ls -la /mnt/%s\n"+
						"# Check disk usage:\n"+
						"df -h /mnt/%s\n\n",
					share.Name, share.Name,
				)

				// Unmount command
				m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
					"# Unmount when done:\n"+
						"sudo umount /mnt/%s\n\n",
					share.Name,
				)
			}
		}
	}
}

func (m *FilestoreModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Location",
		"Tier",
		"Protocol",
		"Network",
		"IP",
		"Shares",
		"Access",
		"Security",
		"State",
	}

	var body [][]string
	for _, instance := range m.Instances {
		var shareNames []string
		var accessModes []string
		hasNoRootSquash := false

		for _, share := range instance.Shares {
			shareNames = append(shareNames, fmt.Sprintf("%s (%dGB)", share.Name, share.CapacityGB))
			for _, opt := range share.NfsExportOptions {
				if opt.AccessMode != "" {
					accessModes = append(accessModes, opt.AccessMode)
				}
				if opt.SquashMode == "NO_ROOT_SQUASH" {
					hasNoRootSquash = true
				}
			}
		}

		ip := strings.Join(instance.IPAddresses, ", ")
		if ip == "" {
			ip = "-"
		}

		shares := strings.Join(shareNames, ", ")
		if shares == "" {
			shares = "-"
		}

		network := instance.Network
		if network == "" {
			network = "-"
		}

		protocol := instance.Protocol
		if protocol == "" {
			protocol = "NFS_V3"
		}

		// Deduplicate and format access modes
		access := "-"
		if len(accessModes) > 0 {
			uniqueAccess := make(map[string]bool)
			for _, a := range accessModes {
				uniqueAccess[a] = true
			}
			var accessList []string
			for a := range uniqueAccess {
				accessList = append(accessList, a)
			}
			access = strings.Join(accessList, ", ")
		}

		// Security findings
		security := "OK"
		if hasNoRootSquash {
			security = "NO_ROOT_SQUASH"
		}

		body = append(body, []string{
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
			instance.Name,
			instance.Location,
			instance.Tier,
			protocol,
			network,
			ip,
			shares,
			access,
			security,
			instance.State,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := FilestoreOutput{
		Table: []internal.TableFile{{Name: "filestore", Header: header, Body: body}},
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
}
