package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	iapservice "github.com/BishopFox/cloudfox/gcp/services/iapService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPIAPCommand = &cobra.Command{
	Use:     globals.GCP_IAP_MODULE_NAME,
	Aliases: []string{"identity-aware-proxy"},
	Short:   "Enumerate Identity-Aware Proxy configurations",
	Long: `Enumerate Identity-Aware Proxy (IAP) configurations.

Features:
- Lists IAP tunnel destination groups
- Analyzes IAP settings and bindings
- Identifies overly permissive tunnel configurations
- Checks for public access to IAP resources`,
	Run: runGCPIAPCommand,
}

type IAPModule struct {
	gcpinternal.BaseGCPModule
	TunnelDestGroups []iapservice.TunnelDestGroup
	LootMap          map[string]*internal.LootFile
	mu               sync.Mutex
}

type IAPOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o IAPOutput) TableFiles() []internal.TableFile { return o.Table }
func (o IAPOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPIAPCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_IAP_MODULE_NAME)
	if err != nil {
		return
	}

	module := &IAPModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		TunnelDestGroups: []iapservice.TunnelDestGroup{},
		LootMap:          make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *IAPModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_IAP_MODULE_NAME, m.processProject)

	if len(m.TunnelDestGroups) == 0 {
		logger.InfoM("No IAP tunnel destination groups found", globals.GCP_IAP_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d IAP tunnel destination group(s)",
		len(m.TunnelDestGroups)), globals.GCP_IAP_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *IAPModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating IAP in project: %s", projectID), globals.GCP_IAP_MODULE_NAME)
	}

	svc := iapservice.New()

	// Get tunnel destination groups
	groups, err := svc.ListTunnelDestGroups(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_IAP_MODULE_NAME,
			fmt.Sprintf("Could not enumerate IAP tunnel groups in project %s", projectID))
	} else {
		m.mu.Lock()
		m.TunnelDestGroups = append(m.TunnelDestGroups, groups...)
		for _, group := range groups {
			m.addToLoot(group)
		}
		m.mu.Unlock()
	}
}

func (m *IAPModule) initializeLootFiles() {
	m.LootMap["iap-tunnel-groups"] = &internal.LootFile{
		Name:     "iap-tunnel-groups",
		Contents: "# IAP Tunnel Destination Groups\n# Generated by CloudFox\n\n",
	}
	m.LootMap["iap-tunnel-cidrs"] = &internal.LootFile{
		Name:     "iap-tunnel-cidrs",
		Contents: "",
	}
}

func (m *IAPModule) addToLoot(group iapservice.TunnelDestGroup) {
	m.LootMap["iap-tunnel-groups"].Contents += fmt.Sprintf(
		"# Group: %s\n# Region: %s\n# CIDRs: %s\n# FQDNs: %s\n\n",
		group.Name, group.Region,
		strings.Join(group.CIDRs, ", "),
		strings.Join(group.FQDNs, ", "))

	for _, cidr := range group.CIDRs {
		m.LootMap["iap-tunnel-cidrs"].Contents += fmt.Sprintf("%s # %s\n", cidr, group.Name)
	}
}

func (m *IAPModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Tunnel Destination Groups table
	header := []string{"Name", "Region", "CIDRs", "FQDNs", "Risk", "Project Name", "Project"}
	var body [][]string
	for _, group := range m.TunnelDestGroups {
		cidrs := strings.Join(group.CIDRs, ", ")
		if len(cidrs) > 40 {
			cidrs = cidrs[:37] + "..."
		}
		fqdns := strings.Join(group.FQDNs, ", ")
		if len(fqdns) > 40 {
			fqdns = fqdns[:37] + "..."
		}

		body = append(body, []string{
			group.Name,
			group.Region,
			cidrs,
			fqdns,
			group.RiskLevel,
			m.GetProjectName(group.ProjectID),
			group.ProjectID,
		})
	}
	tables = append(tables, internal.TableFile{
		Name:   "iap-tunnel-groups",
		Header: header,
		Body:   body,
	})

	// High-risk findings
	var highRiskBody [][]string
	for _, group := range m.TunnelDestGroups {
		if group.RiskLevel == "HIGH" || group.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				group.Name,
				group.RiskLevel,
				strings.Join(group.RiskReasons, "; "),
				m.GetProjectName(group.ProjectID),
				group.ProjectID,
			})
		}
	}

	if len(highRiskBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "iap-risks",
			Header: []string{"Group", "Risk Level", "Reasons", "Project Name", "Project"},
			Body:   highRiskBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := IAPOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_IAP_MODULE_NAME)
	}
}
