package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	loadbalancerservice "github.com/BishopFox/cloudfox/gcp/services/loadbalancerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPLoadBalancersCommand = &cobra.Command{
	Use:     globals.GCP_LOADBALANCERS_MODULE_NAME,
	Aliases: []string{"lb", "lbs"},
	Short:   "Enumerate Load Balancers",
	Long: `Enumerate Load Balancers and related configurations.

Features:
- Lists all forwarding rules (global and regional)
- Shows backend services and health checks
- Analyzes SSL policies for weak configurations
- Identifies external vs internal load balancers
- Checks for Cloud Armor security policies`,
	Run: runGCPLoadBalancersCommand,
}

type LoadBalancersModule struct {
	gcpinternal.BaseGCPModule
	LoadBalancers   []loadbalancerservice.LoadBalancerInfo
	SSLPolicies     []loadbalancerservice.SSLPolicyInfo
	BackendServices []loadbalancerservice.BackendServiceInfo
	LootMap         map[string]*internal.LootFile
	mu              sync.Mutex
}

type LoadBalancersOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o LoadBalancersOutput) TableFiles() []internal.TableFile { return o.Table }
func (o LoadBalancersOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPLoadBalancersCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_LOADBALANCERS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &LoadBalancersModule{
		BaseGCPModule:   gcpinternal.NewBaseGCPModule(cmdCtx),
		LoadBalancers:   []loadbalancerservice.LoadBalancerInfo{},
		SSLPolicies:     []loadbalancerservice.SSLPolicyInfo{},
		BackendServices: []loadbalancerservice.BackendServiceInfo{},
		LootMap:         make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *LoadBalancersModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_LOADBALANCERS_MODULE_NAME, m.processProject)

	if len(m.LoadBalancers) == 0 {
		logger.InfoM("No load balancers found", globals.GCP_LOADBALANCERS_MODULE_NAME)
		return
	}

	externalCount := 0
	for _, lb := range m.LoadBalancers {
		if lb.Scheme == "EXTERNAL" {
			externalCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d load balancer(s) (%d external), %d SSL policies, %d backend services",
		len(m.LoadBalancers), externalCount, len(m.SSLPolicies), len(m.BackendServices)), globals.GCP_LOADBALANCERS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *LoadBalancersModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating load balancers in project: %s", projectID), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}

	svc := loadbalancerservice.New()

	// Get load balancers
	lbs, err := svc.ListLoadBalancers(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_LOADBALANCERS_MODULE_NAME,
			fmt.Sprintf("Could not list load balancers in project %s", projectID))
	} else {
		m.mu.Lock()
		m.LoadBalancers = append(m.LoadBalancers, lbs...)
		m.mu.Unlock()
	}

	// Get SSL policies
	sslPolicies, err := svc.ListSSLPolicies(projectID)
	if err == nil {
		m.mu.Lock()
		m.SSLPolicies = append(m.SSLPolicies, sslPolicies...)
		m.mu.Unlock()
	}

	// Get backend services
	backends, err := svc.ListBackendServices(projectID)
	if err == nil {
		m.mu.Lock()
		m.BackendServices = append(m.BackendServices, backends...)
		m.mu.Unlock()
	}

	m.mu.Lock()
	for _, lb := range lbs {
		m.addToLoot(lb)
	}
	m.mu.Unlock()
}

func (m *LoadBalancersModule) initializeLootFiles() {
	m.LootMap["load-balancers"] = &internal.LootFile{
		Name:     "load-balancers",
		Contents: "# Load Balancers\n# Generated by CloudFox\n\n",
	}
	m.LootMap["external-ips"] = &internal.LootFile{
		Name:     "lb-external-ips",
		Contents: "",
	}
}

func (m *LoadBalancersModule) addToLoot(lb loadbalancerservice.LoadBalancerInfo) {
	m.LootMap["load-balancers"].Contents += fmt.Sprintf(
		"# LB: %s\n# Type: %s\n# Scheme: %s\n# IP: %s\n# Port: %s\n\n",
		lb.Name, lb.Type, lb.Scheme, lb.IPAddress, lb.Port)

	if lb.Scheme == "EXTERNAL" && lb.IPAddress != "" {
		m.LootMap["external-ips"].Contents += fmt.Sprintf("%s # %s (%s)\n", lb.IPAddress, lb.Name, lb.Type)
	}
}

func (m *LoadBalancersModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Load Balancers table
	lbHeader := []string{"Name", "Type", "Scheme", "IP Address", "Port", "Region", "Risk", "Project Name", "Project"}
	var lbBody [][]string
	for _, lb := range m.LoadBalancers {
		lbBody = append(lbBody, []string{
			lb.Name,
			lb.Type,
			lb.Scheme,
			lb.IPAddress,
			lb.Port,
			lb.Region,
			lb.RiskLevel,
			m.GetProjectName(lb.ProjectID),
			lb.ProjectID,
		})
	}
	tables = append(tables, internal.TableFile{
		Name:   "load-balancers",
		Header: lbHeader,
		Body:   lbBody,
	})

	// SSL Policies table
	if len(m.SSLPolicies) > 0 {
		sslHeader := []string{"Name", "Min TLS", "Profile", "Risk", "Project Name", "Project"}
		var sslBody [][]string
		for _, policy := range m.SSLPolicies {
			sslBody = append(sslBody, []string{
				policy.Name,
				policy.MinTLSVersion,
				policy.Profile,
				policy.RiskLevel,
				m.GetProjectName(policy.ProjectID),
				policy.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "ssl-policies",
			Header: sslHeader,
			Body:   sslBody,
		})
	}

	// Backend Services table
	if len(m.BackendServices) > 0 {
		beHeader := []string{"Name", "Protocol", "Security Policy", "CDN", "Health Check", "Risk", "Project Name", "Project"}
		var beBody [][]string
		for _, be := range m.BackendServices {
			cdn := "No"
			if be.EnableCDN {
				cdn = "Yes"
			}
			secPolicy := be.SecurityPolicy
			if secPolicy == "" {
				secPolicy = "(none)"
			}
			beBody = append(beBody, []string{
				be.Name,
				be.Protocol,
				secPolicy,
				cdn,
				be.HealthCheck,
				be.RiskLevel,
				m.GetProjectName(be.ProjectID),
				be.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "backend-services",
			Header: beHeader,
			Body:   beBody,
		})
	}

	// High-risk findings table
	var highRiskBody [][]string
	for _, lb := range m.LoadBalancers {
		if lb.RiskLevel == "HIGH" || lb.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				"LoadBalancer",
				lb.Name,
				lb.RiskLevel,
				strings.Join(lb.RiskReasons, "; "),
				m.GetProjectName(lb.ProjectID),
				lb.ProjectID,
			})
		}
	}
	for _, policy := range m.SSLPolicies {
		if policy.RiskLevel == "HIGH" || policy.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				"SSLPolicy",
				policy.Name,
				policy.RiskLevel,
				strings.Join(policy.RiskReasons, "; "),
				m.GetProjectName(policy.ProjectID),
				policy.ProjectID,
			})
		}
	}

	if len(highRiskBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "lb-risks",
			Header: []string{"Type", "Name", "Risk Level", "Reasons", "Project Name", "Project"},
			Body:   highRiskBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := LoadBalancersOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}
}
