package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	memorystoreservice "github.com/BishopFox/cloudfox/gcp/services/memorystoreService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPMemorystoreCommand = &cobra.Command{
	Use:     globals.GCP_MEMORYSTORE_MODULE_NAME,
	Aliases: []string{"redis", "cache"},
	Short:   "Enumerate Memorystore (Redis) instances",
	Long: `Enumerate Memorystore for Redis instances with security analysis.

Features:
- Lists all Redis instances
- Shows authentication and encryption status
- Identifies network configuration
- Detects security misconfigurations`,
	Run: runGCPMemorystoreCommand,
}

type MemorystoreModule struct {
	gcpinternal.BaseGCPModule
	RedisInstances []memorystoreservice.RedisInstanceInfo
	LootMap        map[string]*internal.LootFile
	mu             sync.Mutex
}

type MemorystoreOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o MemorystoreOutput) TableFiles() []internal.TableFile { return o.Table }
func (o MemorystoreOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPMemorystoreCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_MEMORYSTORE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &MemorystoreModule{
		BaseGCPModule:  gcpinternal.NewBaseGCPModule(cmdCtx),
		RedisInstances: []memorystoreservice.RedisInstanceInfo{},
		LootMap:        make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *MemorystoreModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_MEMORYSTORE_MODULE_NAME, m.processProject)

	if len(m.RedisInstances) == 0 {
		logger.InfoM("No Memorystore instances found", globals.GCP_MEMORYSTORE_MODULE_NAME)
		return
	}

	noAuth := 0
	for _, instance := range m.RedisInstances {
		if !instance.AuthEnabled {
			noAuth++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Redis instance(s) (%d without auth)",
		len(m.RedisInstances), noAuth), globals.GCP_MEMORYSTORE_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

func (m *MemorystoreModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Memorystore in project: %s", projectID), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}

	svc := memorystoreservice.New()
	instances, err := svc.ListRedisInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_MEMORYSTORE_MODULE_NAME,
			fmt.Sprintf("Could not list Redis instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.RedisInstances = append(m.RedisInstances, instances...)
	for _, instance := range instances {
		m.addInstanceToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *MemorystoreModule) initializeLootFiles() {
	m.LootMap["memorystore-instances"] = &internal.LootFile{
		Name:     "memorystore-instances",
		Contents: "# Memorystore Redis Instances\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-endpoints"] = &internal.LootFile{
		Name:     "memorystore-endpoints",
		Contents: "",
	}
	m.LootMap["memorystore-gcloud-commands"] = &internal.LootFile{
		Name:     "memorystore-gcloud-commands",
		Contents: "# Memorystore gcloud Commands\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-no-auth"] = &internal.LootFile{
		Name:     "memorystore-no-auth",
		Contents: "# Redis Instances WITHOUT Authentication\n# These instances have no AUTH - anyone with network access can connect\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-no-encryption"] = &internal.LootFile{
		Name:     "memorystore-no-encryption",
		Contents: "# Redis Instances WITHOUT Transit Encryption\n# Traffic to these instances is unencrypted\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-networks"] = &internal.LootFile{
		Name:     "memorystore-networks",
		Contents: "# Redis Instance Network Configuration\n# Shows which VPCs can access each instance\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-exploitation"] = &internal.LootFile{
		Name:     "memorystore-exploitation",
		Contents: "# Memorystore Exploitation Commands\n# WARNING: Only use with proper authorization\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-security-recommendations"] = &internal.LootFile{
		Name:     "memorystore-security-recommendations",
		Contents: "# Memorystore Security Recommendations\n# Generated by CloudFox\n\n",
	}
}

func (m *MemorystoreModule) addInstanceToLoot(instance memorystoreservice.RedisInstanceInfo) {
	// Basic instance info
	m.LootMap["memorystore-instances"].Contents += fmt.Sprintf(
		"# Instance: %s\n# Host: %s:%d\n# Auth: %v\n# Encryption: %s\n\n",
		instance.Name,
		instance.Host,
		instance.Port,
		instance.AuthEnabled,
		instance.TransitEncryption,
	)
	m.LootMap["memorystore-endpoints"].Contents += fmt.Sprintf("%s:%d\n", instance.Host, instance.Port)

	// gcloud commands
	m.LootMap["memorystore-gcloud-commands"].Contents += fmt.Sprintf(
		"# Instance: %s (Project: %s, Region: %s)\n"+
			"gcloud redis instances describe %s --region=%s --project=%s\n"+
			"gcloud redis instances get-auth-string %s --region=%s --project=%s\n\n",
		instance.Name, instance.ProjectID, instance.Location,
		instance.Name, instance.Location, instance.ProjectID,
		instance.Name, instance.Location, instance.ProjectID,
	)

	// No-auth instances
	if !instance.AuthEnabled {
		m.LootMap["memorystore-no-auth"].Contents += fmt.Sprintf(
			"# INSTANCE: %s\n"+
				"# Project: %s\n"+
				"# Location: %s\n"+
				"# Host: %s:%d\n"+
				"# Network: %s\n"+
				"# RISK: No authentication - anyone with VPC access can connect!\n"+
				"redis-cli -h %s -p %d\n\n",
			instance.Name,
			instance.ProjectID,
			instance.Location,
			instance.Host, instance.Port,
			extractNetworkName(instance.AuthorizedNetwork),
			instance.Host, instance.Port,
		)
	}

	// No-encryption instances
	if instance.TransitEncryption == "DISABLED" || instance.TransitEncryption == "" {
		m.LootMap["memorystore-no-encryption"].Contents += fmt.Sprintf(
			"# INSTANCE: %s\n"+
				"# Project: %s\n"+
				"# Location: %s\n"+
				"# Host: %s:%d\n"+
				"# RISK: No transit encryption - traffic is unencrypted!\n"+
				"# Enable encryption (requires downtime):\n"+
				"gcloud redis instances update %s --region=%s --project=%s --transit-encryption-mode=SERVER_AUTHENTICATION\n\n",
			instance.Name,
			instance.ProjectID,
			instance.Location,
			instance.Host, instance.Port,
			instance.Name, instance.Location, instance.ProjectID,
		)
	}

	// Network configuration
	m.LootMap["memorystore-networks"].Contents += fmt.Sprintf(
		"# Instance: %s (Project: %s)\n"+
			"# Host: %s:%d\n"+
			"# Authorized Network: %s\n"+
			"# Connect Mode: %s\n"+
			"# Reserved IP Range: %s\n\n",
		instance.Name, instance.ProjectID,
		instance.Host, instance.Port,
		instance.AuthorizedNetwork,
		instance.ConnectMode,
		instance.ReservedIPRange,
	)

	// Exploitation commands
	authStr := ""
	if instance.AuthEnabled {
		authStr = " -a $(gcloud redis instances get-auth-string " + instance.Name +
			" --region=" + instance.Location + " --project=" + instance.ProjectID +
			" --format='value(authString)')"
	}
	m.LootMap["memorystore-exploitation"].Contents += fmt.Sprintf(
		"# Instance: %s (Project: %s)\n"+
			"# Host: %s:%d\n"+
			"# Auth: %v, Encryption: %s\n"+
			"# Risk Level: %s\n\n"+
			"# Connect to Redis (from a VM in the same VPC):\n"+
			"redis-cli -h %s -p %d%s\n\n"+
			"# Common Redis commands for enumeration:\n"+
			"# INFO                    - Server info and stats\n"+
			"# CONFIG GET *            - All configuration\n"+
			"# KEYS *                  - List all keys (CAREFUL: may be slow)\n"+
			"# SCAN 0 COUNT 100        - Iterate keys safely\n"+
			"# GET key                 - Get value\n"+
			"# DBSIZE                  - Number of keys\n\n",
		instance.Name, instance.ProjectID,
		instance.Host, instance.Port,
		instance.AuthEnabled, instance.TransitEncryption,
		instance.RiskLevel,
		instance.Host, instance.Port, authStr,
	)

	// Add security recommendations
	m.addRedisSecurityRecommendations(instance)
}

// extractNetworkName extracts the network name from the full resource path
func extractNetworkName(network string) string {
	if network == "" {
		return "default"
	}
	parts := strings.Split(network, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return network
}

// addRedisSecurityRecommendations generates security recommendations for a Redis instance
func (m *MemorystoreModule) addRedisSecurityRecommendations(instance memorystoreservice.RedisInstanceInfo) {
	var recommendations []string

	// No authentication - CRITICAL
	if !instance.AuthEnabled {
		recommendations = append(recommendations,
			fmt.Sprintf("[CRITICAL] Instance %s has NO authentication enabled\n"+
				"  Risk: Anyone with network access to the VPC can connect and read/write data\n"+
				"  Fix: Enable AUTH (requires recreating instance):\n"+
				"  gcloud redis instances create %s-new --region=%s --project=%s --auth-enabled\n",
				instance.Name,
				instance.Name, instance.Location, instance.ProjectID))
	}

	// No transit encryption - HIGH
	if instance.TransitEncryption == "DISABLED" || instance.TransitEncryption == "" {
		recommendations = append(recommendations,
			fmt.Sprintf("[HIGH] Instance %s has NO transit encryption\n"+
				"  Risk: Redis traffic can be sniffed on the network\n"+
				"  Fix: Enable transit encryption:\n"+
				"  gcloud redis instances update %s --region=%s --project=%s --transit-encryption-mode=SERVER_AUTHENTICATION\n",
				instance.Name,
				instance.Name, instance.Location, instance.ProjectID))
	}

	// Basic tier (no HA) - MEDIUM
	if instance.Tier == "BASIC" {
		recommendations = append(recommendations,
			fmt.Sprintf("[MEDIUM] Instance %s uses BASIC tier (no high availability)\n"+
				"  Risk: Single point of failure, no automatic failover\n"+
				"  Consider: Upgrading to STANDARD_HA tier for production workloads\n"+
				"  gcloud redis instances create %s-ha --region=%s --project=%s --tier=STANDARD_HA\n",
				instance.Name,
				instance.Name, instance.Location, instance.ProjectID))
	}

	// Default network - LOW
	if strings.Contains(instance.AuthorizedNetwork, "/default") {
		recommendations = append(recommendations,
			fmt.Sprintf("[LOW] Instance %s is connected to the default network\n"+
				"  Risk: Default networks have broad firewall rules\n"+
				"  Consider: Using a dedicated VPC with restricted access\n",
				instance.Name))
	}

	// Old Redis version - INFO
	if strings.HasPrefix(instance.RedisVersion, "REDIS_4") || strings.HasPrefix(instance.RedisVersion, "REDIS_5") {
		recommendations = append(recommendations,
			fmt.Sprintf("[INFO] Instance %s uses an older Redis version: %s\n"+
				"  Note: Consider upgrading to Redis 7.x for better security and performance\n"+
				"  gcloud redis instances upgrade %s --redis-version=redis_7_0 --region=%s --project=%s\n",
				instance.Name, instance.RedisVersion,
				instance.Name, instance.Location, instance.ProjectID))
	}

	if len(recommendations) > 0 {
		m.LootMap["memorystore-security-recommendations"].Contents += fmt.Sprintf(
			"# Instance: %s (Project: %s)\n%s\n",
			instance.Name, instance.ProjectID,
			strings.Join(recommendations, "\n"))
	}
}

func (m *MemorystoreModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Name",
		"Location",
		"Tier",
		"Memory (GB)",
		"Version",
		"Host:Port",
		"Auth",
		"Encryption",
		"State",
		"Risk",
		"Project Name",
		"Project",
	}

	var body [][]string
	for _, instance := range m.RedisInstances {
		auth := "No"
		if instance.AuthEnabled {
			auth = "Yes"
		}
		body = append(body, []string{
			instance.Name,
			instance.Location,
			instance.Tier,
			fmt.Sprintf("%d", instance.MemorySizeGB),
			instance.RedisVersion,
			fmt.Sprintf("%s:%d", instance.Host, instance.Port),
			auth,
			instance.TransitEncryption,
			instance.State,
			instance.RiskLevel,
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{{Name: "memorystore", Header: header, Body: body}}

	output := MemorystoreOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}
}
