package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	notebooksservice "github.com/BishopFox/cloudfox/gcp/services/notebooksService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPNotebooksCommand = &cobra.Command{
	Use:     globals.GCP_NOTEBOOKS_MODULE_NAME,
	Aliases: []string{"nb", "jupyter", "workbench"},
	Short:   "Enumerate Vertex AI Workbench notebooks",
	Long: `Enumerate Vertex AI Workbench and legacy notebook instances.

Features:
- Lists all notebook instances across locations
- Shows service account configuration
- Identifies public IP exposure
- Checks for GPU attachments
- Analyzes proxy access settings`,
	Run: runGCPNotebooksCommand,
}

type NotebooksModule struct {
	gcpinternal.BaseGCPModule
	Instances []notebooksservice.NotebookInstanceInfo
	Runtimes  []notebooksservice.RuntimeInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type NotebooksOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o NotebooksOutput) TableFiles() []internal.TableFile { return o.Table }
func (o NotebooksOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPNotebooksCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_NOTEBOOKS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &NotebooksModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []notebooksservice.NotebookInstanceInfo{},
		Runtimes:      []notebooksservice.RuntimeInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *NotebooksModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_NOTEBOOKS_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 && len(m.Runtimes) == 0 {
		logger.InfoM("No notebook instances found", globals.GCP_NOTEBOOKS_MODULE_NAME)
		return
	}

	publicCount := 0
	for _, instance := range m.Instances {
		if !instance.NoPublicIP {
			publicCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d notebook instance(s) (%d with public IP), %d runtime(s)",
		len(m.Instances), publicCount, len(m.Runtimes)), globals.GCP_NOTEBOOKS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *NotebooksModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating notebooks in project: %s", projectID), globals.GCP_NOTEBOOKS_MODULE_NAME)
	}

	svc := notebooksservice.New()

	// Get instances
	instances, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_NOTEBOOKS_MODULE_NAME,
			fmt.Sprintf("Could not list notebook instances in project %s", projectID))
	} else {
		m.mu.Lock()
		m.Instances = append(m.Instances, instances...)
		for _, instance := range instances {
			m.addToLoot(instance)
		}
		m.mu.Unlock()
	}

	// Get runtimes
	runtimes, err := svc.ListRuntimes(projectID)
	if err == nil {
		m.mu.Lock()
		m.Runtimes = append(m.Runtimes, runtimes...)
		m.mu.Unlock()
	}
}

func (m *NotebooksModule) initializeLootFiles() {
	m.LootMap["notebooks"] = &internal.LootFile{
		Name:     "notebooks",
		Contents: "# Notebook Instances\n# Generated by CloudFox\n\n",
	}
	m.LootMap["notebook-service-accounts"] = &internal.LootFile{
		Name:     "notebook-service-accounts",
		Contents: "",
	}
}

func (m *NotebooksModule) addToLoot(instance notebooksservice.NotebookInstanceInfo) {
	m.LootMap["notebooks"].Contents += fmt.Sprintf(
		"# Instance: %s\n# Location: %s\n# State: %s\n# Service Account: %s\n# Public IP: %v\n\n",
		instance.Name, instance.Location, instance.State, instance.ServiceAccount, !instance.NoPublicIP)

	if instance.ServiceAccount != "" {
		m.LootMap["notebook-service-accounts"].Contents += instance.ServiceAccount + "\n"
	}
}

func (m *NotebooksModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Instances table
	if len(m.Instances) > 0 {
		header := []string{"Name", "Location", "State", "Machine Type", "Service Account", "Public IP", "GPU", "Risk", "Project Name", "Project"}
		var body [][]string
		for _, instance := range m.Instances {
			publicIP := "No"
			if !instance.NoPublicIP {
				publicIP = "Yes"
			}
			gpu := "None"
			if instance.AcceleratorCount > 0 {
				gpu = fmt.Sprintf("%s x%d", instance.AcceleratorType, instance.AcceleratorCount)
			}
			sa := instance.ServiceAccount
			if sa == "" {
				sa = "(default)"
			} else if len(sa) > 40 {
				sa = sa[:37] + "..."
			}
			body = append(body, []string{
				instance.Name,
				instance.Location,
				instance.State,
				instance.MachineType,
				sa,
				publicIP,
				gpu,
				instance.RiskLevel,
				m.GetProjectName(instance.ProjectID),
				instance.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "notebook-instances",
			Header: header,
			Body:   body,
		})
	}

	// Runtimes table
	if len(m.Runtimes) > 0 {
		header := []string{"Name", "Location", "State", "Type", "Machine Type", "Risk", "Project Name", "Project"}
		var body [][]string
		for _, runtime := range m.Runtimes {
			body = append(body, []string{
				runtime.Name,
				runtime.Location,
				runtime.State,
				runtime.RuntimeType,
				runtime.MachineType,
				runtime.RiskLevel,
				m.GetProjectName(runtime.ProjectID),
				runtime.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "notebook-runtimes",
			Header: header,
			Body:   body,
		})
	}

	// High-risk findings
	var highRiskBody [][]string
	for _, instance := range m.Instances {
		if instance.RiskLevel == "HIGH" || instance.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				instance.Name,
				instance.RiskLevel,
				strings.Join(instance.RiskReasons, "; "),
				m.GetProjectName(instance.ProjectID),
				instance.ProjectID,
			})
		}
	}

	if len(highRiskBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "notebook-risks",
			Header: []string{"Instance", "Risk Level", "Reasons", "Project Name", "Project"},
			Body:   highRiskBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := NotebooksOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_NOTEBOOKS_MODULE_NAME)
	}
}
