package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	publicresourcesservice "github.com/BishopFox/cloudfox/gcp/services/publicResourcesService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPPublicResourcesCommand = &cobra.Command{
	Use:     globals.GCP_PUBLICRESOURCES_MODULE_NAME,
	Aliases: []string{"public", "exposed", "internet-facing"},
	Short:   "Enumerate all internet-exposed resources",
	Long: `Consolidate and enumerate all internet-exposed GCP resources.

This module provides a single view of your attack surface by identifying
resources accessible from the internet across multiple services.

Resources Scanned:
- Compute Engine instances with external IPs
- Cloud SQL instances with public IPs
- Cloud Run services with public ingress
- Cloud Functions with allUsers/allAuthenticatedUsers
- GKE clusters with public API endpoints
- Cloud Storage buckets with public access
- External load balancers

Output:
- Consolidated table of all public resources
- Risk levels (CRITICAL, HIGH, MEDIUM, LOW)
- Access methods and exploitation commands
- Service account associations

Use this for initial attack surface mapping during engagements.`,
	Run: runGCPPublicResourcesCommand,
}

// ------------------------------
// Module Struct
// ------------------------------
type PublicResourcesModule struct {
	gcpinternal.BaseGCPModule

	Resources []publicresourcesservice.PublicResource
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

// ------------------------------
// Output Struct
// ------------------------------
type PublicResourcesOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o PublicResourcesOutput) TableFiles() []internal.TableFile { return o.Table }
func (o PublicResourcesOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPPublicResourcesCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_PUBLICRESOURCES_MODULE_NAME)
	if err != nil {
		return
	}

	module := &PublicResourcesModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Resources:     []publicresourcesservice.PublicResource{},
		LootMap:       make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *PublicResourcesModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_PUBLICRESOURCES_MODULE_NAME, m.processProject)

	if len(m.Resources) == 0 {
		logger.InfoM("No public resources found", globals.GCP_PUBLICRESOURCES_MODULE_NAME)
		return
	}

	// Count by risk level
	criticalCount := 0
	highCount := 0
	for _, r := range m.Resources {
		switch r.RiskLevel {
		case "CRITICAL":
			criticalCount++
		case "HIGH":
			highCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d public resource(s)", len(m.Resources)), globals.GCP_PUBLICRESOURCES_MODULE_NAME)
	if criticalCount > 0 || highCount > 0 {
		logger.InfoM(fmt.Sprintf("[ATTACK SURFACE] %d CRITICAL, %d HIGH risk public resources!", criticalCount, highCount), globals.GCP_PUBLICRESOURCES_MODULE_NAME)
	}

	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *PublicResourcesModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Scanning public resources in project: %s", projectID), globals.GCP_PUBLICRESOURCES_MODULE_NAME)
	}

	svc := publicresourcesservice.New()
	resources, err := svc.EnumeratePublicResources(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_PUBLICRESOURCES_MODULE_NAME,
			fmt.Sprintf("Could not enumerate public resources in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Resources = append(m.Resources, resources...)

	for _, resource := range resources {
		m.addResourceToLoot(resource)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d public resource(s) in project %s", len(resources), projectID), globals.GCP_PUBLICRESOURCES_MODULE_NAME)
	}
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *PublicResourcesModule) initializeLootFiles() {
	m.LootMap["public-resources-all"] = &internal.LootFile{
		Name:     "public-resources-all",
		Contents: "# All Public Resources\n# Generated by CloudFox\n\n",
	}
	m.LootMap["public-resources-critical"] = &internal.LootFile{
		Name:     "public-resources-critical",
		Contents: "# CRITICAL Risk Public Resources\n# Generated by CloudFox\n# These require immediate attention\n\n",
	}
	m.LootMap["public-resources-exploit"] = &internal.LootFile{
		Name:     "public-resources-exploit",
		Contents: "# Public Resource Exploitation Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
	m.LootMap["public-endpoints"] = &internal.LootFile{
		Name:     "public-endpoints",
		Contents: "# Public Endpoints (for scanning)\n# Generated by CloudFox\n\n",
	}
}

func (m *PublicResourcesModule) addResourceToLoot(resource publicresourcesservice.PublicResource) {
	// Add to all resources
	m.LootMap["public-resources-all"].Contents += fmt.Sprintf(
		"## [%s] %s: %s\n"+
			"## Project: %s, Location: %s\n"+
			"## Endpoint: %s\n"+
			"## Access: %s\n\n",
		resource.RiskLevel, resource.ResourceType, resource.Name,
		resource.ProjectID, resource.Location,
		resource.PublicEndpoint,
		resource.AccessLevel,
	)

	// Add critical resources separately
	if resource.RiskLevel == "CRITICAL" {
		m.LootMap["public-resources-critical"].Contents += fmt.Sprintf(
			"## [CRITICAL] %s: %s\n"+
				"## Project: %s\n"+
				"## Endpoint: %s\n"+
				"## Access: %s\n"+
				"## Reasons:\n",
			resource.ResourceType, resource.Name,
			resource.ProjectID,
			resource.PublicEndpoint,
			resource.AccessLevel,
		)
		for _, reason := range resource.RiskReasons {
			m.LootMap["public-resources-critical"].Contents += fmt.Sprintf("##   - %s\n", reason)
		}
		m.LootMap["public-resources-critical"].Contents += "\n"
	}

	// Add exploit commands
	if len(resource.ExploitCommands) > 0 {
		m.LootMap["public-resources-exploit"].Contents += fmt.Sprintf(
			"## [%s] %s: %s (%s)\n",
			resource.RiskLevel, resource.ResourceType, resource.Name, resource.ProjectID,
		)
		for _, cmd := range resource.ExploitCommands {
			m.LootMap["public-resources-exploit"].Contents += cmd + "\n"
		}
		m.LootMap["public-resources-exploit"].Contents += "\n"
	}

	// Add to endpoints list for scanning
	if resource.PublicEndpoint != "" {
		m.LootMap["public-endpoints"].Contents += resource.PublicEndpoint + "\n"
	}
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *PublicResourcesModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Main resources table
	header := []string{
		"Risk",
		"Type",
		"Name",
		"Endpoint",
		"Port",
		"Access Level",
		"Service Account",
		"Project Name",
		"Project",
	}

	var body [][]string
	for _, resource := range m.Resources {
		saDisplay := resource.ServiceAccount
		if saDisplay != "" && len(saDisplay) > 30 {
			parts := strings.Split(saDisplay, "@")
			if len(parts) > 0 {
				saDisplay = parts[0] + "@..."
			}
		}
		if saDisplay == "" {
			saDisplay = "-"
		}

		endpoint := resource.PublicEndpoint
		if len(endpoint) > 50 {
			endpoint = endpoint[:50] + "..."
		}

		body = append(body, []string{
			resource.RiskLevel,
			resource.ResourceType,
			resource.Name,
			endpoint,
			resource.Port,
			resource.AccessLevel,
			saDisplay,
			m.GetProjectName(resource.ProjectID),
			resource.ProjectID,
		})
	}

	// By resource type table
	typeHeader := []string{
		"Resource Type",
		"Count",
		"Critical",
		"High",
	}

	typeCounts := make(map[string]struct {
		total    int
		critical int
		high     int
	})

	for _, resource := range m.Resources {
		counts := typeCounts[resource.ResourceType]
		counts.total++
		if resource.RiskLevel == "CRITICAL" {
			counts.critical++
		} else if resource.RiskLevel == "HIGH" {
			counts.high++
		}
		typeCounts[resource.ResourceType] = counts
	}

	var typeBody [][]string
	for resourceType, counts := range typeCounts {
		typeBody = append(typeBody, []string{
			resourceType,
			fmt.Sprintf("%d", counts.total),
			fmt.Sprintf("%d", counts.critical),
			fmt.Sprintf("%d", counts.high),
		})
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	// Build tables
	tables := []internal.TableFile{
		{
			Name:   "public-resources",
			Header: header,
			Body:   body,
		},
	}

	if len(typeBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "public-resources-summary",
			Header: typeHeader,
			Body:   typeBody,
		})
	}

	output := PublicResourcesOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_PUBLICRESOURCES_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
