package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	sourcereposservice "github.com/BishopFox/cloudfox/gcp/services/sourceReposService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPSourceReposCommand = &cobra.Command{
	Use:     globals.GCP_SOURCEREPOS_MODULE_NAME,
	Aliases: []string{"repos", "csr", "git"},
	Short:   "Enumerate Cloud Source Repositories",
	Long: `Enumerate Cloud Source Repositories for code and secrets.

Cloud Source Repositories can contain:
- Application source code
- Infrastructure as Code (Terraform, CloudFormation)
- Configuration files with hardcoded credentials
- API keys and secrets in code
- CI/CD pipeline configurations

Output:
- List of all repositories accessible
- Repository sizes and mirror configurations
- Clone commands for each repository
- Secret search commands

After cloning, search for:
- Hardcoded credentials and API keys
- Private keys and certificates
- Environment configuration files
- Database connection strings`,
	Run: runGCPSourceReposCommand,
}

// ------------------------------
// Module Struct
// ------------------------------
type SourceReposModule struct {
	gcpinternal.BaseGCPModule

	Repos   []sourcereposservice.RepoInfo
	LootMap map[string]*internal.LootFile
	mu      sync.Mutex
}

// ------------------------------
// Output Struct
// ------------------------------
type SourceReposOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SourceReposOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SourceReposOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPSourceReposCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SOURCEREPOS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &SourceReposModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Repos:         []sourcereposservice.RepoInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *SourceReposModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SOURCEREPOS_MODULE_NAME, m.processProject)

	if len(m.Repos) == 0 {
		logger.InfoM("No Cloud Source Repositories found", globals.GCP_SOURCEREPOS_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d repository(ies)", len(m.Repos)), globals.GCP_SOURCEREPOS_MODULE_NAME)
	logger.InfoM("[PENTEST] Clone repositories and search for secrets!", globals.GCP_SOURCEREPOS_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *SourceReposModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Cloud Source Repositories in project: %s", projectID), globals.GCP_SOURCEREPOS_MODULE_NAME)
	}

	svc := sourcereposservice.New()
	repos, err := svc.ListRepos(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SOURCEREPOS_MODULE_NAME,
			fmt.Sprintf("Could not list repos in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Repos = append(m.Repos, repos...)

	for _, repo := range repos {
		m.addRepoToLoot(repo)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d repository(ies) in project %s", len(repos), projectID), globals.GCP_SOURCEREPOS_MODULE_NAME)
	}
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *SourceReposModule) initializeLootFiles() {
	m.LootMap["source-repos-clone"] = &internal.LootFile{
		Name:     "source-repos-clone",
		Contents: "# Cloud Source Repository Clone Commands\n# Generated by CloudFox\n\n",
	}
	m.LootMap["source-repos-secrets-search"] = &internal.LootFile{
		Name:     "source-repos-secrets-search",
		Contents: "# Search Cloned Repos for Secrets\n# Generated by CloudFox\n# Run after cloning repositories\n\n",
	}
}

func (m *SourceReposModule) addRepoToLoot(repo sourcereposservice.RepoInfo) {
	// Clone commands
	m.LootMap["source-repos-clone"].Contents += fmt.Sprintf(
		"# Repository: %s (Project: %s)\n",
		repo.Name, repo.ProjectID,
	)
	if repo.Size > 0 {
		m.LootMap["source-repos-clone"].Contents += fmt.Sprintf("# Size: %d bytes\n", repo.Size)
	}
	if repo.MirrorConfig {
		m.LootMap["source-repos-clone"].Contents += fmt.Sprintf("# Mirrors: %s\n", repo.MirrorURL)
	}
	m.LootMap["source-repos-clone"].Contents += fmt.Sprintf(
		"gcloud source repos clone %s --project=%s\n\n",
		repo.Name, repo.ProjectID,
	)

	// Secret search commands
	m.LootMap["source-repos-secrets-search"].Contents += fmt.Sprintf(
		"# Search %s for secrets:\n"+
			"cd %s\n"+
			"grep -rE '(password|secret|api[_-]?key|private[_-]?key|AWS_|GOOGLE_|token)' . --include='*'\n"+
			"find . -name '*.pem' -o -name '*.key' -o -name '.env*' -o -name '*credential*' -o -name '*.tfvars'\n"+
			"grep -rE 'BEGIN (RSA |DSA |EC |OPENSSH )?PRIVATE KEY' .\n\n",
		repo.Name, repo.Name,
	)
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *SourceReposModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Repos table
	header := []string{
		"Name",
		"Size",
		"Mirror",
		"Triggers",
		"Risk",
		"Project Name",
		"Project",
	}

	var body [][]string
	for _, repo := range m.Repos {
		sizeDisplay := "-"
		if repo.Size > 0 {
			if repo.Size > 1024*1024 {
				sizeDisplay = fmt.Sprintf("%.1f MB", float64(repo.Size)/(1024*1024))
			} else if repo.Size > 1024 {
				sizeDisplay = fmt.Sprintf("%.1f KB", float64(repo.Size)/1024)
			} else {
				sizeDisplay = fmt.Sprintf("%d B", repo.Size)
			}
		}

		mirror := "No"
		if repo.MirrorConfig {
			mirror = "Yes"
		}

		body = append(body, []string{
			repo.Name,
			sizeDisplay,
			mirror,
			fmt.Sprintf("%d", repo.PubsubConfigs),
			repo.RiskLevel,
			m.GetProjectName(repo.ProjectID),
			repo.ProjectID,
		})
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{
		{
			Name:   "source-repos",
			Header: header,
			Body:   body,
		},
	}

	output := SourceReposOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_SOURCEREPOS_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
