package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	spannerservice "github.com/BishopFox/cloudfox/gcp/services/spannerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPSpannerCommand = &cobra.Command{
	Use:     globals.GCP_SPANNER_MODULE_NAME,
	Aliases: []string{"cloud-spanner"},
	Short:   "Enumerate Cloud Spanner instances and databases",
	Long:    `Enumerate Cloud Spanner instances and their databases.`,
	Run:     runGCPSpannerCommand,
}

type SpannerModule struct {
	gcpinternal.BaseGCPModule
	Instances []spannerservice.SpannerInstanceInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type SpannerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SpannerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SpannerOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPSpannerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SPANNER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &SpannerModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []spannerservice.SpannerInstanceInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *SpannerModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SPANNER_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 {
		logger.InfoM("No Spanner instances found", globals.GCP_SPANNER_MODULE_NAME)
		return
	}

	dbCount := 0
	for _, instance := range m.Instances {
		dbCount += len(instance.Databases)
	}

	logger.SuccessM(fmt.Sprintf("Found %d Spanner instance(s) with %d database(s)",
		len(m.Instances), dbCount), globals.GCP_SPANNER_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *SpannerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	svc := spannerservice.New()
	instances, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SPANNER_MODULE_NAME,
			fmt.Sprintf("Could not list Spanner instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Instances = append(m.Instances, instances...)
	for _, instance := range instances {
		m.addToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *SpannerModule) initializeLootFiles() {
	m.LootMap["spanner-instances"] = &internal.LootFile{
		Name:     "spanner-instances",
		Contents: "# Spanner Instances and Databases\n# Generated by CloudFox\n\n",
	}
}

func (m *SpannerModule) addToLoot(instance spannerservice.SpannerInstanceInfo) {
	m.LootMap["spanner-instances"].Contents += fmt.Sprintf(
		"# Instance: %s (%s)\n# Databases: %s\n# Nodes: %d\n\n",
		instance.Name, instance.DisplayName,
		strings.Join(instance.Databases, ", "),
		instance.NodeCount)
}

func (m *SpannerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{"Name", "Display Name", "Config", "Nodes", "Databases", "State", "Project Name", "Project"}

	var body [][]string
	for _, instance := range m.Instances {
		body = append(body, []string{
			instance.Name,
			instance.DisplayName,
			instance.Config,
			fmt.Sprintf("%d", instance.NodeCount),
			strings.Join(instance.Databases, ", "),
			instance.State,
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := SpannerOutput{
		Table: []internal.TableFile{{Name: "spanner", Header: header, Body: body}},
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
}
