package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	vpcservice "github.com/BishopFox/cloudfox/gcp/services/vpcService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPVPCNetworksCommand = &cobra.Command{
	Use:     globals.GCP_VPCNETWORKS_MODULE_NAME,
	Aliases: []string{"vpc", "networks", "net"},
	Short:   "Enumerate VPC Networks",
	Long: `Enumerate VPC Networks and related configurations.

Features:
- Lists all VPC networks and subnets
- Shows VPC peering connections
- Analyzes routing tables
- Checks for Private Google Access
- Identifies flow log configuration`,
	Run: runGCPVPCNetworksCommand,
}

type VPCNetworksModule struct {
	gcpinternal.BaseGCPModule
	Networks []vpcservice.VPCNetworkInfo
	Subnets  []vpcservice.SubnetInfo
	Peerings []vpcservice.VPCPeeringInfo
	Routes   []vpcservice.RouteInfo
	LootMap  map[string]*internal.LootFile
	mu       sync.Mutex
}

type VPCNetworksOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o VPCNetworksOutput) TableFiles() []internal.TableFile { return o.Table }
func (o VPCNetworksOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPVPCNetworksCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_VPCNETWORKS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &VPCNetworksModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Networks:      []vpcservice.VPCNetworkInfo{},
		Subnets:       []vpcservice.SubnetInfo{},
		Peerings:      []vpcservice.VPCPeeringInfo{},
		Routes:        []vpcservice.RouteInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *VPCNetworksModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_VPCNETWORKS_MODULE_NAME, m.processProject)

	if len(m.Networks) == 0 {
		logger.InfoM("No VPC networks found", globals.GCP_VPCNETWORKS_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d VPC network(s), %d subnet(s), %d peering(s), %d route(s)",
		len(m.Networks), len(m.Subnets), len(m.Peerings), len(m.Routes)), globals.GCP_VPCNETWORKS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *VPCNetworksModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating VPC networks in project: %s", projectID), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}

	svc := vpcservice.New()

	// Get networks
	networks, err := svc.ListVPCNetworks(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCNETWORKS_MODULE_NAME,
			fmt.Sprintf("Could not list VPC networks in project %s", projectID))
	} else {
		m.mu.Lock()
		m.Networks = append(m.Networks, networks...)
		m.mu.Unlock()
	}

	// Get subnets
	subnets, err := svc.ListSubnets(projectID)
	if err == nil {
		m.mu.Lock()
		m.Subnets = append(m.Subnets, subnets...)
		m.mu.Unlock()
	}

	// Get peerings
	peerings, err := svc.ListVPCPeerings(projectID)
	if err == nil {
		m.mu.Lock()
		m.Peerings = append(m.Peerings, peerings...)
		m.mu.Unlock()
	}

	// Get routes
	routes, err := svc.ListRoutes(projectID)
	if err == nil {
		m.mu.Lock()
		m.Routes = append(m.Routes, routes...)
		m.mu.Unlock()
	}

	m.mu.Lock()
	for _, network := range networks {
		m.addNetworkToLoot(network)
	}
	for _, subnet := range subnets {
		m.addSubnetToLoot(subnet)
	}
	for _, peering := range peerings {
		m.addPeeringToLoot(peering)
	}
	m.mu.Unlock()
}

func (m *VPCNetworksModule) initializeLootFiles() {
	m.LootMap["vpc-networks"] = &internal.LootFile{
		Name:     "vpc-networks",
		Contents: "# VPC Networks\n# Generated by CloudFox\n\n",
	}
	m.LootMap["subnet-cidrs"] = &internal.LootFile{
		Name:     "subnet-cidrs",
		Contents: "",
	}
	m.LootMap["vpc-lateral-movement"] = &internal.LootFile{
		Name:     "vpc-lateral-movement",
		Contents: "# VPC Lateral Movement Paths\n# Generated by CloudFox\n# Cross-project VPC peerings for network pivoting\n\n",
	}
	m.LootMap["vpc-peering-commands"] = &internal.LootFile{
		Name:     "vpc-peering-commands",
		Contents: "# VPC Peering Exploitation Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *VPCNetworksModule) addNetworkToLoot(network vpcservice.VPCNetworkInfo) {
	m.LootMap["vpc-networks"].Contents += fmt.Sprintf(
		"# Network: %s\n# Routing: %s\n# Subnets: %d\n# Peerings: %d\n\n",
		network.Name, network.RoutingMode, len(network.Subnetworks), len(network.Peerings))
}

func (m *VPCNetworksModule) addSubnetToLoot(subnet vpcservice.SubnetInfo) {
	m.LootMap["subnet-cidrs"].Contents += fmt.Sprintf("%s # %s/%s\n",
		subnet.IPCidrRange, subnet.Network, subnet.Name)
}

func (m *VPCNetworksModule) addPeeringToLoot(peering vpcservice.VPCPeeringInfo) {
	// Add lateral movement paths
	if peering.LateralMovementPath {
		m.LootMap["vpc-lateral-movement"].Contents += fmt.Sprintf(
			"## [%s] %s -> %s\n"+
				"## Source Project: %s\n"+
				"## Target Project: %s\n"+
				"## State: %s\n",
			peering.RiskLevel, peering.Network, peering.PeerNetwork,
			peering.ProjectID, peering.PeerProjectID,
			peering.State,
		)
		for _, reason := range peering.RiskReasons {
			m.LootMap["vpc-lateral-movement"].Contents += fmt.Sprintf("##   - %s\n", reason)
		}
		m.LootMap["vpc-lateral-movement"].Contents += "\n"
	}

	// Add exploitation commands
	if len(peering.ExploitCommands) > 0 {
		m.LootMap["vpc-peering-commands"].Contents += fmt.Sprintf(
			"## [%s] Peering: %s (Project: %s)\n",
			peering.RiskLevel, peering.Name, peering.ProjectID,
		)
		for _, cmd := range peering.ExploitCommands {
			m.LootMap["vpc-peering-commands"].Contents += cmd + "\n"
		}
		m.LootMap["vpc-peering-commands"].Contents += "\n"
	}
}

func (m *VPCNetworksModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Networks table
	netHeader := []string{"Name", "Routing Mode", "Auto Subnets", "Subnets", "Peerings", "Risk", "Project Name", "Project"}
	var netBody [][]string
	for _, network := range m.Networks {
		autoSubnets := "No"
		if network.AutoCreateSubnetworks {
			autoSubnets = "Yes"
		}
		netBody = append(netBody, []string{
			network.Name,
			network.RoutingMode,
			autoSubnets,
			fmt.Sprintf("%d", len(network.Subnetworks)),
			fmt.Sprintf("%d", len(network.Peerings)),
			network.RiskLevel,
			m.GetProjectName(network.ProjectID),
			network.ProjectID,
		})
	}
	tables = append(tables, internal.TableFile{
		Name:   "vpc-networks",
		Header: netHeader,
		Body:   netBody,
	})

	// Subnets table
	if len(m.Subnets) > 0 {
		subHeader := []string{"Name", "Network", "Region", "CIDR", "Private Access", "Flow Logs", "Risk", "Project Name", "Project"}
		var subBody [][]string
		for _, subnet := range m.Subnets {
			privateAccess := "No"
			if subnet.PrivateIPGoogleAccess {
				privateAccess = "Yes"
			}
			flowLogs := "No"
			if subnet.EnableFlowLogs {
				flowLogs = "Yes"
			}
			subBody = append(subBody, []string{
				subnet.Name,
				subnet.Network,
				subnet.Region,
				subnet.IPCidrRange,
				privateAccess,
				flowLogs,
				subnet.RiskLevel,
				m.GetProjectName(subnet.ProjectID),
				subnet.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "subnets",
			Header: subHeader,
			Body:   subBody,
		})
	}

	// Peerings table
	if len(m.Peerings) > 0 {
		peerHeader := []string{"Name", "Network", "Peer Network", "Peer Project", "State", "Lateral Move", "Risk", "Project Name", "Project"}
		var peerBody [][]string
		for _, peering := range m.Peerings {
			lateralMove := "No"
			if peering.LateralMovementPath {
				lateralMove = "YES"
			}
			peerProject := peering.PeerProjectID
			if peerProject == "" {
				peerProject = "-"
			}
			peerBody = append(peerBody, []string{
				peering.Name,
				peering.Network,
				peering.PeerNetwork,
				peerProject,
				peering.State,
				lateralMove,
				peering.RiskLevel,
				m.GetProjectName(peering.ProjectID),
				peering.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "vpc-peerings",
			Header: peerHeader,
			Body:   peerBody,
		})
	}

	// Routes table (custom routes only, skip default)
	var customRoutes []vpcservice.RouteInfo
	for _, route := range m.Routes {
		if !strings.HasPrefix(route.Name, "default-route-") {
			customRoutes = append(customRoutes, route)
		}
	}
	if len(customRoutes) > 0 {
		routeHeader := []string{"Name", "Network", "Dest Range", "Next Hop Type", "Next Hop", "Priority", "Project Name", "Project"}
		var routeBody [][]string
		for _, route := range customRoutes {
			routeBody = append(routeBody, []string{
				route.Name,
				route.Network,
				route.DestRange,
				route.NextHopType,
				route.NextHop,
				fmt.Sprintf("%d", route.Priority),
				m.GetProjectName(route.ProjectID),
				route.ProjectID,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "custom-routes",
			Header: routeHeader,
			Body:   routeBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := VPCNetworksOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}
}
