package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	orgsservice "github.com/BishopFox/cloudfox/gcp/services/organizationsService"
	vpcscservice "github.com/BishopFox/cloudfox/gcp/services/vpcscService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var orgID string

var GCPVPCSCCommand = &cobra.Command{
	Use:     globals.GCP_VPCSC_MODULE_NAME,
	Aliases: []string{"vpcsc", "service-controls", "sc"},
	Short:   "Enumerate VPC Service Controls",
	Long: `Enumerate VPC Service Controls configuration.

Features:
- Lists access policies for the organization
- Enumerates service perimeters (regular and bridge)
- Shows access levels and their conditions
- Identifies overly permissive configurations
- Analyzes ingress/egress policies

Note: Organization ID is auto-discovered from project ancestry. Use --org flag to override.`,
	Run: runGCPVPCSCCommand,
}

func init() {
	GCPVPCSCCommand.Flags().StringVar(&orgID, "org", "", "Organization ID (auto-discovered if not provided)")
}

type VPCSCModule struct {
	gcpinternal.BaseGCPModule
	OrgID        string
	Policies     []vpcscservice.AccessPolicyInfo
	Perimeters   []vpcscservice.ServicePerimeterInfo
	AccessLevels []vpcscservice.AccessLevelInfo
	LootMap      map[string]*internal.LootFile
	mu           sync.Mutex
}

type VPCSCOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o VPCSCOutput) TableFiles() []internal.TableFile { return o.Table }
func (o VPCSCOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPVPCSCCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_VPCSC_MODULE_NAME)
	if err != nil {
		return
	}

	// Auto-discover org ID if not provided
	effectiveOrgID := orgID
	if effectiveOrgID == "" {
		if len(cmdCtx.ProjectIDs) == 0 {
			cmdCtx.Logger.ErrorM("No projects discovered and no --org flag provided. Cannot determine organization.", globals.GCP_VPCSC_MODULE_NAME)
			return
		}

		cmdCtx.Logger.InfoM("Auto-discovering organization ID from project ancestry...", globals.GCP_VPCSC_MODULE_NAME)
		orgsSvc := orgsservice.New()

		// Try to get org ID from the first project
		discoveredOrgID, err := orgsSvc.GetOrganizationIDFromProject(cmdCtx.ProjectIDs[0])
		if err != nil {
			cmdCtx.Logger.ErrorM(fmt.Sprintf("Could not auto-discover organization ID: %v. Use --org flag to specify.", err), globals.GCP_VPCSC_MODULE_NAME)
			return
		}

		effectiveOrgID = discoveredOrgID
		cmdCtx.Logger.InfoM(fmt.Sprintf("Discovered organization ID: %s", effectiveOrgID), globals.GCP_VPCSC_MODULE_NAME)
	}

	module := &VPCSCModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		OrgID:         effectiveOrgID,
		Policies:      []vpcscservice.AccessPolicyInfo{},
		Perimeters:    []vpcscservice.ServicePerimeterInfo{},
		AccessLevels:  []vpcscservice.AccessLevelInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *VPCSCModule) Execute(ctx context.Context, logger internal.Logger) {
	logger.InfoM(fmt.Sprintf("Enumerating VPC Service Controls for organization: %s", m.OrgID), globals.GCP_VPCSC_MODULE_NAME)

	svc := vpcscservice.New()

	// List access policies
	policies, err := svc.ListAccessPolicies(m.OrgID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCSC_MODULE_NAME,
			fmt.Sprintf("Could not list access policies for organization %s", m.OrgID))
		return
	}
	m.Policies = policies

	if len(m.Policies) == 0 {
		logger.InfoM("No access policies found", globals.GCP_VPCSC_MODULE_NAME)
		return
	}

	// For each policy, list perimeters and access levels
	for _, policy := range m.Policies {
		perimeters, err := svc.ListServicePerimeters(policy.Name)
		if err != nil {
			gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCSC_MODULE_NAME,
				fmt.Sprintf("Could not list perimeters for policy %s", policy.Name))
		} else {
			m.Perimeters = append(m.Perimeters, perimeters...)
		}

		levels, err := svc.ListAccessLevels(policy.Name)
		if err != nil {
			gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCSC_MODULE_NAME,
				fmt.Sprintf("Could not list access levels for policy %s", policy.Name))
		} else {
			m.AccessLevels = append(m.AccessLevels, levels...)
		}
	}

	m.addAllToLoot()

	logger.SuccessM(fmt.Sprintf("Found %d access policy(ies), %d perimeter(s), %d access level(s)",
		len(m.Policies), len(m.Perimeters), len(m.AccessLevels)), globals.GCP_VPCSC_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *VPCSCModule) initializeLootFiles() {
	m.LootMap["vpcsc-perimeters"] = &internal.LootFile{
		Name:     "vpcsc-perimeters",
		Contents: "# VPC Service Control Perimeters\n# Generated by CloudFox\n\n",
	}
	m.LootMap["vpcsc-protected-projects"] = &internal.LootFile{
		Name:     "vpcsc-protected-projects",
		Contents: "",
	}
}

func (m *VPCSCModule) addAllToLoot() {
	for _, perimeter := range m.Perimeters {
		m.LootMap["vpcsc-perimeters"].Contents += fmt.Sprintf(
			"# Perimeter: %s\n# Type: %s\n# Resources: %d\n# Restricted Services: %d\n\n",
			perimeter.Title, perimeter.PerimeterType,
			len(perimeter.Resources), len(perimeter.RestrictedServices))

		for _, resource := range perimeter.Resources {
			m.LootMap["vpcsc-protected-projects"].Contents += resource + "\n"
		}
	}
}

func (m *VPCSCModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Access Policies table
	if len(m.Policies) > 0 {
		policyHeader := []string{"Name", "Title", "Parent", "Created", "Updated"}
		var policyBody [][]string
		for _, policy := range m.Policies {
			policyBody = append(policyBody, []string{
				policy.Name,
				policy.Title,
				policy.Parent,
				policy.CreateTime,
				policy.UpdateTime,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "vpcsc-policies",
			Header: policyHeader,
			Body:   policyBody,
		})
	}

	// Service Perimeters table
	if len(m.Perimeters) > 0 {
		perimeterHeader := []string{
			"Name", "Title", "Type", "Resources", "Restricted Services",
			"Ingress Policies", "Egress Policies", "Risk", "Policy",
		}
		var perimeterBody [][]string
		for _, perimeter := range m.Perimeters {
			perimeterBody = append(perimeterBody, []string{
				perimeter.Name,
				perimeter.Title,
				perimeter.PerimeterType,
				fmt.Sprintf("%d", len(perimeter.Resources)),
				fmt.Sprintf("%d", len(perimeter.RestrictedServices)),
				fmt.Sprintf("%d", perimeter.IngressPolicyCount),
				fmt.Sprintf("%d", perimeter.EgressPolicyCount),
				perimeter.RiskLevel,
				perimeter.PolicyName,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "vpcsc-perimeters",
			Header: perimeterHeader,
			Body:   perimeterBody,
		})
	}

	// Access Levels table
	if len(m.AccessLevels) > 0 {
		levelHeader := []string{"Name", "Title", "IP Subnets", "Regions", "Members", "Risk", "Policy"}
		var levelBody [][]string
		for _, level := range m.AccessLevels {
			levelBody = append(levelBody, []string{
				level.Name,
				level.Title,
				strings.Join(level.IPSubnetworks, ", "),
				strings.Join(level.Regions, ", "),
				fmt.Sprintf("%d", len(level.Members)),
				level.RiskLevel,
				level.PolicyName,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "vpcsc-access-levels",
			Header: levelHeader,
			Body:   levelBody,
		})
	}

	// High-risk findings table
	var highRiskBody [][]string
	for _, perimeter := range m.Perimeters {
		if perimeter.RiskLevel == "HIGH" || perimeter.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				"Perimeter",
				perimeter.Name,
				perimeter.RiskLevel,
				strings.Join(perimeter.RiskReasons, "; "),
			})
		}
	}
	for _, level := range m.AccessLevels {
		if level.RiskLevel == "HIGH" || level.RiskLevel == "MEDIUM" {
			highRiskBody = append(highRiskBody, []string{
				"AccessLevel",
				level.Name,
				level.RiskLevel,
				strings.Join(level.RiskReasons, "; "),
			})
		}
	}

	if len(highRiskBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "vpcsc-risks",
			Header: []string{"Type", "Name", "Risk Level", "Reasons"},
			Body:   highRiskBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := VPCSCOutput{Table: tables, Loot: lootFiles}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"org", []string{m.OrgID}, []string{m.OrgID}, m.Account, output)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCSC_MODULE_NAME,
			"Could not write output")
	}
}
